---
title: "bayesynergy: flexible Bayesian modelling of synergistic interaction effects in in-vitro drug combination experiments"
author: "Leiv Rønneberg"
date: "05/09/2022"
output: 
  rmarkdown::html_vignette:
    toc: true
bibliography: references.bib
vignette: >
  \usepackage[utf8]{inputenc}
  %\VignetteIndexEntry{bayesynergy: flexible Bayesian modelling of synergistic interaction effects in in-vitro drug combination experiments}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 100px;
}
```


# Introduction

The `bayesynergy` R package implements a Bayesian semi-parametric
regression model for estimating the dose-response function of *in-vitro*
drug combination experiments. The Bayesian framework offers full
uncertainty quantification of the dose response function and any derived
summary statistics, as well as natural handling of replicates and
missing data. The Bayesian model is implemented in Stan (@Stan_2020),
taking advantage of the efficient 'No U-Turn Sampler' as well as
variational Bayes for quick approximations of the true posterior.

The package is further equipped with plotting functions for summarizing
a drug response experiment, parallel processing for large drug
combination screen, as well as plotting tools for summarizing and
comparing these.



# A simple example -- a single experiment

In the R package, we've attached two example datasets from a large drug
combination screening experiment on diffuse large B-cell lymphoma. We'll use these to show some simple use cases of the main functions and how to interpret the results.

Let's load in the first example and have a look at it




# References
