###### Script for generating plots for the bayesynergy paper

# The dataset is from [1] and has been preprocessed according to the function preprocess.R

# For Figure 4, we include a subset of this dataset, consisting of 3498 experiments
# on six breast cancer cell lines. This dataset has been run through the synergyscreen
# function on default settings, and the file "screen.RData" contains the resulting object.

# For Figure 5 and Table 1, the data must be generated according to the instructions in 
# preprocess.R

########################################################################################
############################    FIG 4   ################################################
###### Drug combination screen on breast cancer cell line     ##########################
########################################################################################
library(bayesynergy)

# Data for figure 4 is included in the folder
load("screen.RData")

plot(fit_screen,save_plots=T,plotdevice="png", width=7,height=7,units="in",res=600, 
     groupbyExperimentID=F)


########################################################################################
############################    FIG 5   ################################################
###### Gemcitabine + MK-8776 on the OCUBM cell line     ################################
########################################################################################
# The file "OCUBM : Gemcitabine + MK-8776.csv" can be generated by following instructions 
# in preprocess.R

data = read.table("OCUBM : Gemcitabine + MK-8776.csv",sep=",",header=T)

x = as.matrix(data[,c(4,6)])
y = data$viability
drug_names = c(data$drugA_name[1],data$drugB_name[1])
experiment_ID = data$cell_line[1]
units = c("μM","μM")

fit = bayesynergy(y=y, x=x, drug_names=drug_names, experiment_ID = experiment_ID, units=units)

plot(fit,save_plots=T, plotdevice="png", width=7,height=7,units="in",res=600, plot3D=F)



########################################################################################
############################    Table 1   ##############################################
###### Gemcitabine + MK-8776 on the OCUBM cell line     ################################
########################################################################################
summary(fit)





# References:
# [1]
# Jennifer O'Neil, Yair Benita, Igor Feldman, Melissa Chenard, Brian Roberts, Yaping Liu, Jing Li, Astrid Kral, Serguei Lejnine, Andrey Loboda, William Arthur, Razvan Cristescu, Brian B. Haines, Christopher Winter, Theresa Zhang, Andrew Bloecher and Stuart D. Shumway
# Mol Cancer Ther June 1 2016 (15) (6) 1155-1162; DOI: 10.1158/1535-7163.MCT-15-0843




