// Generated by rstantools.  Do not edit by hand.

/*
    bayesynergy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bayesynergy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bayesynergy.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_nointeraction_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_nointeraction");
    reader.add_event(2, 2, "include", "/include/VUS.stan");
    reader.add_event(2, 0, "start", "/include/VUS.stan");
    reader.add_event(22, 20, "end", "/include/VUS.stan");
    reader.add_event(22, 3, "restart", "model_nointeraction");
    reader.add_event(22, 3, "include", "/include/lptn.stan");
    reader.add_event(22, 0, "start", "/include/lptn.stan");
    reader.add_event(37, 15, "end", "/include/lptn.stan");
    reader.add_event(37, 4, "restart", "model_nointeraction");
    reader.add_event(37, 4, "include", "/include/dss.stan");
    reader.add_event(37, 0, "start", "/include/dss.stan");
    reader.add_event(42, 5, "end", "/include/dss.stan");
    reader.add_event(42, 5, "restart", "model_nointeraction");
    reader.add_event(224, 185, "end", "model_nointeraction");
    return reader;
}
template <typename T0__, typename T1__, typename T2__>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
VUS(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& Z,
        const std::vector<T1__>& x1,
        const std::vector<T2__>& x2, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 5;
        validate_non_negative_index("d", "2", 2);
        std::vector<int  > d(2, int(0));
        stan::math::fill(d, std::numeric_limits<int>::min());
        stan::math::assign(d,dims(Z));
        current_statement_begin__ = 6;
        int n1(0);
        (void) n1;  // dummy to suppress unused var warning
        stan::math::fill(n1, std::numeric_limits<int>::min());
        stan::math::assign(n1,get_base1(d, 2, "d", 1));
        current_statement_begin__ = 7;
        int n2(0);
        (void) n2;  // dummy to suppress unused var warning
        stan::math::fill(n2, std::numeric_limits<int>::min());
        stan::math::assign(n2,get_base1(d, 1, "d", 1));
        current_statement_begin__ = 8;
        local_scalar_t__ rVUS(DUMMY_VAR__);
        (void) rVUS;  // dummy to suppress unused var warning
        stan::math::initialize(rVUS, DUMMY_VAR__);
        stan::math::fill(rVUS, DUMMY_VAR__);
        stan::math::assign(rVUS,0);
        current_statement_begin__ = 9;
        validate_non_negative_index("B_rVUS", "n2", n2);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> B_rVUS(n2);
        stan::math::initialize(B_rVUS, DUMMY_VAR__);
        stan::math::fill(B_rVUS, DUMMY_VAR__);
        current_statement_begin__ = 10;
        for (int i = 1; i <= n2; ++i) {
            {
            current_statement_begin__ = 11;
            local_scalar_t__ b_rVUS(DUMMY_VAR__);
            (void) b_rVUS;  // dummy to suppress unused var warning
            stan::math::initialize(b_rVUS, DUMMY_VAR__);
            stan::math::fill(b_rVUS, DUMMY_VAR__);
            stan::math::assign(b_rVUS,0);
            current_statement_begin__ = 12;
            for (int j = 2; j <= n1; ++j) {
                current_statement_begin__ = 13;
                stan::math::assign(b_rVUS, (b_rVUS + (((get_base1(x1, j, "x1", 1) - get_base1(x1, (j - 1), "x1", 1)) * (get_base1(Z, i, j, "Z", 1) + get_base1(Z, i, (j - 1), "Z", 1))) / 2)));
            }
            current_statement_begin__ = 15;
            stan::model::assign(B_rVUS, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        b_rVUS, 
                        "assigning variable B_rVUS");
            current_statement_begin__ = 16;
            if (as_bool(logical_gt(i, 1))) {
                current_statement_begin__ = 17;
                stan::math::assign(rVUS, (rVUS + (((get_base1(x2, i, "x2", 1) - get_base1(x2, (i - 1), "x2", 1)) * (get_base1(B_rVUS, i, "B_rVUS", 1) + get_base1(B_rVUS, (i - 1), "B_rVUS", 1))) / 2)));
            }
            }
        }
        current_statement_begin__ = 20;
        stan::math::assign(rVUS, ((100 * rVUS) / ((max(x1) - min(x1)) * (max(x2) - min(x2)))));
        current_statement_begin__ = 21;
        return stan::math::promote_scalar<fun_return_scalar_t__>(rVUS);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct VUS_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& Z,
        const std::vector<T1__>& x1,
        const std::vector<T2__>& x2, std::ostream* pstream__) const {
        return VUS(Z, x1, x2, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
lptn(const T0__& rho,
         const T1__& z,
         const T2__& lambda,
         const T3__& tau, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 25;
        if (as_bool(logical_lte(stan::math::fabs(z), tau))) {
            current_statement_begin__ = 26;
            return stan::math::promote_scalar<fun_return_scalar_t__>(std_normal_log(z));
        } else {
            {
            current_statement_begin__ = 29;
            local_scalar_t__ logt(DUMMY_VAR__);
            (void) logt;  // dummy to suppress unused var warning
            stan::math::initialize(logt, DUMMY_VAR__);
            stan::math::fill(logt, DUMMY_VAR__);
            stan::math::assign(logt,stan::math::log(tau));
            current_statement_begin__ = 30;
            local_scalar_t__ logl(DUMMY_VAR__);
            (void) logl;  // dummy to suppress unused var warning
            stan::math::initialize(logl, DUMMY_VAR__);
            stan::math::fill(logl, DUMMY_VAR__);
            stan::math::assign(logl,stan::math::log(lambda));
            current_statement_begin__ = 32;
            local_scalar_t__ logabsz(DUMMY_VAR__);
            (void) logabsz;  // dummy to suppress unused var warning
            stan::math::initialize(logabsz, DUMMY_VAR__);
            stan::math::fill(logabsz, DUMMY_VAR__);
            stan::math::assign(logabsz,stan::math::log(stan::math::fmax(stan::math::fabs(z), 1.0001)));
            current_statement_begin__ = 34;
            local_scalar_t__ lpdf(DUMMY_VAR__);
            (void) lpdf;  // dummy to suppress unused var warning
            stan::math::initialize(lpdf, DUMMY_VAR__);
            stan::math::fill(lpdf, DUMMY_VAR__);
            stan::math::assign(lpdf,(((std_normal_log(tau) + logt) - logabsz) + ((lambda + 1) * (stan::math::log(logt) - stan::math::log(logabsz)))));
            current_statement_begin__ = 35;
            return stan::math::promote_scalar<fun_return_scalar_t__>(lpdf);
            }
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct lptn_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& rho,
         const T1__& z,
         const T2__& lambda,
         const T3__& tau, std::ostream* pstream__) const {
        return lptn(rho, z, lambda, tau, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
dss(const T0__& c1,
        const T1__& c2,
        const T2__& la,
        const T3__& slope,
        const T4__& log10_ec50, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 39;
        local_scalar_t__ val(DUMMY_VAR__);
        (void) val;  // dummy to suppress unused var warning
        stan::math::initialize(val, DUMMY_VAR__);
        stan::math::fill(val, DUMMY_VAR__);
        stan::math::assign(val,((c2 - c1) + (((la - 1) / slope) * (stan::math::log10((1 + pow(10, (slope * (c2 - log10_ec50))))) - stan::math::log10((1 + pow(10, (slope * (c1 - log10_ec50)))))))));
        current_statement_begin__ = 40;
        stan::math::assign(val, (100 * (1 - (val / (c2 - c1)))));
        current_statement_begin__ = 41;
        return stan::math::promote_scalar<fun_return_scalar_t__>(val);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct dss_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& c1,
        const T1__& c2,
        const T2__& la,
        const T3__& slope,
        const T4__& log10_ec50, std::ostream* pstream__) const {
        return dss(c1, c2, la, slope, log10_ec50, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_nointeraction
  : public stan::model::model_base_crtp<model_nointeraction> {
private:
        int n1;
        int n2;
        int nmissing;
        int nrep;
        vector_d y;
        std::vector<int> ii_obs;
        std::vector<double> x1;
        std::vector<double> x2;
        int est_la;
        int heteroscedastic;
        int robust;
        int pcprior;
        vector_d pcprior_hypers;
        double rho;
        double lambda;
        int N;
        double c11;
        double c12;
        double c21;
        double c22;
        double tauLPTN;
        double lambdaLPTN;
public:
    model_nointeraction(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_nointeraction(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_nointeraction_namespace::model_nointeraction";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 45;
            context__.validate_dims("data initialization", "n1", "int", context__.to_vec());
            n1 = int(0);
            vals_i__ = context__.vals_i("n1");
            pos__ = 0;
            n1 = vals_i__[pos__++];
            check_greater_or_equal(function__, "n1", n1, 1);
            current_statement_begin__ = 46;
            context__.validate_dims("data initialization", "n2", "int", context__.to_vec());
            n2 = int(0);
            vals_i__ = context__.vals_i("n2");
            pos__ = 0;
            n2 = vals_i__[pos__++];
            check_greater_or_equal(function__, "n2", n2, 1);
            current_statement_begin__ = 47;
            context__.validate_dims("data initialization", "nmissing", "int", context__.to_vec());
            nmissing = int(0);
            vals_i__ = context__.vals_i("nmissing");
            pos__ = 0;
            nmissing = vals_i__[pos__++];
            check_greater_or_equal(function__, "nmissing", nmissing, 0);
            current_statement_begin__ = 48;
            context__.validate_dims("data initialization", "nrep", "int", context__.to_vec());
            nrep = int(0);
            vals_i__ = context__.vals_i("nrep");
            pos__ = 0;
            nrep = vals_i__[pos__++];
            check_greater_or_equal(function__, "nrep", nrep, 1);
            current_statement_begin__ = 49;
            validate_non_negative_index("y", "(((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)", (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing));
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec((((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>((((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing);
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 50;
            validate_non_negative_index("ii_obs", "(((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)", (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing));
            context__.validate_dims("data initialization", "ii_obs", "int", context__.to_vec((((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)));
            ii_obs = std::vector<int>((((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing), int(0));
            vals_i__ = context__.vals_i("ii_obs");
            pos__ = 0;
            size_t ii_obs_k_0_max__ = (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing);
            for (size_t k_0__ = 0; k_0__ < ii_obs_k_0_max__; ++k_0__) {
                ii_obs[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 51;
            validate_non_negative_index("x1", "n1", n1);
            context__.validate_dims("data initialization", "x1", "double", context__.to_vec(n1));
            x1 = std::vector<double>(n1, double(0));
            vals_r__ = context__.vals_r("x1");
            pos__ = 0;
            size_t x1_k_0_max__ = n1;
            for (size_t k_0__ = 0; k_0__ < x1_k_0_max__; ++k_0__) {
                x1[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 52;
            validate_non_negative_index("x2", "n2", n2);
            context__.validate_dims("data initialization", "x2", "double", context__.to_vec(n2));
            x2 = std::vector<double>(n2, double(0));
            vals_r__ = context__.vals_r("x2");
            pos__ = 0;
            size_t x2_k_0_max__ = n2;
            for (size_t k_0__ = 0; k_0__ < x2_k_0_max__; ++k_0__) {
                x2[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 53;
            context__.validate_dims("data initialization", "est_la", "int", context__.to_vec());
            est_la = int(0);
            vals_i__ = context__.vals_i("est_la");
            pos__ = 0;
            est_la = vals_i__[pos__++];
            current_statement_begin__ = 54;
            context__.validate_dims("data initialization", "heteroscedastic", "int", context__.to_vec());
            heteroscedastic = int(0);
            vals_i__ = context__.vals_i("heteroscedastic");
            pos__ = 0;
            heteroscedastic = vals_i__[pos__++];
            current_statement_begin__ = 55;
            context__.validate_dims("data initialization", "robust", "int", context__.to_vec());
            robust = int(0);
            vals_i__ = context__.vals_i("robust");
            pos__ = 0;
            robust = vals_i__[pos__++];
            current_statement_begin__ = 56;
            context__.validate_dims("data initialization", "pcprior", "int", context__.to_vec());
            pcprior = int(0);
            vals_i__ = context__.vals_i("pcprior");
            pos__ = 0;
            pcprior = vals_i__[pos__++];
            current_statement_begin__ = 57;
            validate_non_negative_index("pcprior_hypers", "4", 4);
            context__.validate_dims("data initialization", "pcprior_hypers", "vector_d", context__.to_vec(4));
            pcprior_hypers = Eigen::Matrix<double, Eigen::Dynamic, 1>(4);
            vals_r__ = context__.vals_r("pcprior_hypers");
            pos__ = 0;
            size_t pcprior_hypers_j_1_max__ = 4;
            for (size_t j_1__ = 0; j_1__ < pcprior_hypers_j_1_max__; ++j_1__) {
                pcprior_hypers(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 58;
            context__.validate_dims("data initialization", "rho", "double", context__.to_vec());
            rho = double(0);
            vals_r__ = context__.vals_r("rho");
            pos__ = 0;
            rho = vals_r__[pos__++];
            current_statement_begin__ = 59;
            context__.validate_dims("data initialization", "lambda", "double", context__.to_vec());
            lambda = double(0);
            vals_r__ = context__.vals_r("lambda");
            pos__ = 0;
            lambda = vals_r__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 62;
            N = int(0);
            stan::math::fill(N, std::numeric_limits<int>::min());
            stan::math::assign(N,(((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing));
            current_statement_begin__ = 63;
            c11 = double(0);
            stan::math::fill(c11, DUMMY_VAR__);
            stan::math::assign(c11,min(x1));
            current_statement_begin__ = 64;
            c12 = double(0);
            stan::math::fill(c12, DUMMY_VAR__);
            stan::math::assign(c12,max(x1));
            current_statement_begin__ = 65;
            c21 = double(0);
            stan::math::fill(c21, DUMMY_VAR__);
            stan::math::assign(c21,min(x2));
            current_statement_begin__ = 66;
            c22 = double(0);
            stan::math::fill(c22, DUMMY_VAR__);
            stan::math::assign(c22,max(x2));
            current_statement_begin__ = 67;
            tauLPTN = double(0);
            stan::math::fill(tauLPTN, DUMMY_VAR__);
            stan::math::assign(tauLPTN,inv_Phi(((1 + rho) / 2)));
            current_statement_begin__ = 68;
            lambdaLPTN = double(0);
            stan::math::fill(lambdaLPTN, DUMMY_VAR__);
            stan::math::assign(lambdaLPTN,((((2 * inv((1 - rho))) * stan::math::exp(normal_log(tauLPTN, 0, 1))) * tauLPTN) * stan::math::log(tauLPTN)));
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 72;
            validate_non_negative_index("la_1", "(est_la ? 1 : 0 )", (est_la ? 1 : 0 ));
            num_params_r__ += (1 * (est_la ? 1 : 0 ));
            current_statement_begin__ = 73;
            validate_non_negative_index("la_2", "(est_la ? 1 : 0 )", (est_la ? 1 : 0 ));
            num_params_r__ += (1 * (est_la ? 1 : 0 ));
            current_statement_begin__ = 74;
            num_params_r__ += 1;
            current_statement_begin__ = 75;
            num_params_r__ += 1;
            current_statement_begin__ = 76;
            num_params_r__ += 1;
            current_statement_begin__ = 77;
            num_params_r__ += 1;
            current_statement_begin__ = 78;
            num_params_r__ += 1;
            current_statement_begin__ = 79;
            num_params_r__ += 1;
            current_statement_begin__ = 82;
            num_params_r__ += 1;
            current_statement_begin__ = 83;
            num_params_r__ += 1;
            current_statement_begin__ = 84;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_nointeraction() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 72;
        if (!(context__.contains_r("la_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable la_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("la_1");
        pos__ = 0U;
        validate_non_negative_index("la_1", "(est_la ? 1 : 0 )", (est_la ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "la_1", "double", context__.to_vec((est_la ? 1 : 0 )));
        std::vector<double> la_1((est_la ? 1 : 0 ), double(0));
        size_t la_1_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_1_k_0_max__; ++k_0__) {
            la_1[k_0__] = vals_r__[pos__++];
        }
        size_t la_1_i_0_max__ = (est_la ? 1 : 0 );
        for (size_t i_0__ = 0; i_0__ < la_1_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, 1, la_1[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable la_1: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 73;
        if (!(context__.contains_r("la_2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable la_2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("la_2");
        pos__ = 0U;
        validate_non_negative_index("la_2", "(est_la ? 1 : 0 )", (est_la ? 1 : 0 ));
        context__.validate_dims("parameter initialization", "la_2", "double", context__.to_vec((est_la ? 1 : 0 )));
        std::vector<double> la_2((est_la ? 1 : 0 ), double(0));
        size_t la_2_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_2_k_0_max__; ++k_0__) {
            la_2[k_0__] = vals_r__[pos__++];
        }
        size_t la_2_i_0_max__ = (est_la ? 1 : 0 );
        for (size_t i_0__ = 0; i_0__ < la_2_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, 1, la_2[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable la_2: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 74;
        if (!(context__.contains_r("log10_ec50_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log10_ec50_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log10_ec50_1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "log10_ec50_1", "double", context__.to_vec());
        double log10_ec50_1(0);
        log10_ec50_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(log10_ec50_1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log10_ec50_1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 75;
        if (!(context__.contains_r("log10_ec50_2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable log10_ec50_2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("log10_ec50_2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "log10_ec50_2", "double", context__.to_vec());
        double log10_ec50_2(0);
        log10_ec50_2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(log10_ec50_2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable log10_ec50_2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 76;
        if (!(context__.contains_r("theta_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_1", "double", context__.to_vec());
        double theta_1(0);
        theta_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(theta_1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 77;
        if (!(context__.contains_r("theta_2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_2", "double", context__.to_vec());
        double theta_2(0);
        theta_2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(theta_2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 78;
        if (!(context__.contains_r("slope_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable slope_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("slope_1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "slope_1", "double", context__.to_vec());
        double slope_1(0);
        slope_1 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, slope_1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable slope_1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 79;
        if (!(context__.contains_r("slope_2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable slope_2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("slope_2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "slope_2", "double", context__.to_vec());
        double slope_2(0);
        slope_2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, slope_2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable slope_2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 82;
        if (!(context__.contains_r("s")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable s missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("s");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "s", "double", context__.to_vec());
        double s(0);
        s = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, s);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable s: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 83;
        if (!(context__.contains_r("s2_log10_ec50_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable s2_log10_ec50_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("s2_log10_ec50_1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "s2_log10_ec50_1", "double", context__.to_vec());
        double s2_log10_ec50_1(0);
        s2_log10_ec50_1 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, s2_log10_ec50_1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable s2_log10_ec50_1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 84;
        if (!(context__.contains_r("s2_log10_ec50_2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable s2_log10_ec50_2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("s2_log10_ec50_2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "s2_log10_ec50_2", "double", context__.to_vec());
        double s2_log10_ec50_2(0);
        s2_log10_ec50_2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, s2_log10_ec50_2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable s2_log10_ec50_2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 72;
            std::vector<local_scalar_t__> la_1;
            size_t la_1_d_0_max__ = (est_la ? 1 : 0 );
            la_1.reserve(la_1_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < la_1_d_0_max__; ++d_0__) {
                if (jacobian__)
                    la_1.push_back(in__.scalar_lub_constrain(0, 1, lp__));
                else
                    la_1.push_back(in__.scalar_lub_constrain(0, 1));
            }
            current_statement_begin__ = 73;
            std::vector<local_scalar_t__> la_2;
            size_t la_2_d_0_max__ = (est_la ? 1 : 0 );
            la_2.reserve(la_2_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < la_2_d_0_max__; ++d_0__) {
                if (jacobian__)
                    la_2.push_back(in__.scalar_lub_constrain(0, 1, lp__));
                else
                    la_2.push_back(in__.scalar_lub_constrain(0, 1));
            }
            current_statement_begin__ = 74;
            local_scalar_t__ log10_ec50_1;
            (void) log10_ec50_1;  // dummy to suppress unused var warning
            if (jacobian__)
                log10_ec50_1 = in__.scalar_constrain(lp__);
            else
                log10_ec50_1 = in__.scalar_constrain();
            current_statement_begin__ = 75;
            local_scalar_t__ log10_ec50_2;
            (void) log10_ec50_2;  // dummy to suppress unused var warning
            if (jacobian__)
                log10_ec50_2 = in__.scalar_constrain(lp__);
            else
                log10_ec50_2 = in__.scalar_constrain();
            current_statement_begin__ = 76;
            local_scalar_t__ theta_1;
            (void) theta_1;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_1 = in__.scalar_constrain(lp__);
            else
                theta_1 = in__.scalar_constrain();
            current_statement_begin__ = 77;
            local_scalar_t__ theta_2;
            (void) theta_2;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_2 = in__.scalar_constrain(lp__);
            else
                theta_2 = in__.scalar_constrain();
            current_statement_begin__ = 78;
            local_scalar_t__ slope_1;
            (void) slope_1;  // dummy to suppress unused var warning
            if (jacobian__)
                slope_1 = in__.scalar_lb_constrain(0, lp__);
            else
                slope_1 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 79;
            local_scalar_t__ slope_2;
            (void) slope_2;  // dummy to suppress unused var warning
            if (jacobian__)
                slope_2 = in__.scalar_lb_constrain(0, lp__);
            else
                slope_2 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 82;
            local_scalar_t__ s;
            (void) s;  // dummy to suppress unused var warning
            if (jacobian__)
                s = in__.scalar_lb_constrain(0, lp__);
            else
                s = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 83;
            local_scalar_t__ s2_log10_ec50_1;
            (void) s2_log10_ec50_1;  // dummy to suppress unused var warning
            if (jacobian__)
                s2_log10_ec50_1 = in__.scalar_lb_constrain(0, lp__);
            else
                s2_log10_ec50_1 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 84;
            local_scalar_t__ s2_log10_ec50_2;
            (void) s2_log10_ec50_2;  // dummy to suppress unused var warning
            if (jacobian__)
                s2_log10_ec50_2 = in__.scalar_lb_constrain(0, lp__);
            else
                s2_log10_ec50_2 = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 88;
            validate_non_negative_index("p0", "n2", n2);
            validate_non_negative_index("p0", "n1", n1);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> p0(n2, n1);
            stan::math::initialize(p0, DUMMY_VAR__);
            stan::math::fill(p0, DUMMY_VAR__);
            current_statement_begin__ = 89;
            validate_non_negative_index("p01", "n1", n1);
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> p01(n1);
            stan::math::initialize(p01, DUMMY_VAR__);
            stan::math::fill(p01, DUMMY_VAR__);
            current_statement_begin__ = 90;
            validate_non_negative_index("p02", "n2", n2);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> p02(n2);
            stan::math::initialize(p02, DUMMY_VAR__);
            stan::math::fill(p02, DUMMY_VAR__);
            // transformed parameters block statements
            {
            current_statement_begin__ = 93;
            local_scalar_t__ la_1_param(DUMMY_VAR__);
            (void) la_1_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_1_param, DUMMY_VAR__);
            stan::math::fill(la_1_param, DUMMY_VAR__);
            current_statement_begin__ = 94;
            local_scalar_t__ la_2_param(DUMMY_VAR__);
            (void) la_2_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_2_param, DUMMY_VAR__);
            stan::math::fill(la_2_param, DUMMY_VAR__);
            current_statement_begin__ = 96;
            if (as_bool(est_la)) {
                current_statement_begin__ = 97;
                stan::math::assign(la_1_param, get_base1(la_1, 1, "la_1", 1));
                current_statement_begin__ = 98;
                stan::math::assign(la_2_param, get_base1(la_2, 1, "la_2", 1));
            } else {
                current_statement_begin__ = 100;
                stan::math::assign(la_1_param, 0);
                current_statement_begin__ = 101;
                stan::math::assign(la_2_param, 0);
            }
            current_statement_begin__ = 104;
            for (int j = 1; j <= n1; ++j) {
                current_statement_begin__ = 105;
                stan::model::assign(p01, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            (la_1_param + ((1 - la_1_param) / (1 + pow(10, (slope_1 * (get_base1(x1, j, "x1", 1) - log10_ec50_1)))))), 
                            "assigning variable p01");
                current_statement_begin__ = 106;
                for (int i = 1; i <= n2; ++i) {
                    current_statement_begin__ = 107;
                    stan::model::assign(p02, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (la_2_param + ((1 - la_2_param) / (1 + pow(10, (slope_2 * (get_base1(x2, i, "x2", 1) - log10_ec50_2)))))), 
                                "assigning variable p02");
                    current_statement_begin__ = 108;
                    stan::model::assign(p0, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                (get_base1(p01, j, "p01", 1) * get_base1(p02, i, "p02", 1)), 
                                "assigning variable p0");
                }
            }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 88;
            size_t p0_j_1_max__ = n2;
            size_t p0_j_2_max__ = n1;
            for (size_t j_1__ = 0; j_1__ < p0_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < p0_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(p0(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: p0" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable p0: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            check_greater_or_equal(function__, "p0", p0, 0);
            check_less_or_equal(function__, "p0", p0, 1);
            current_statement_begin__ = 89;
            size_t p01_j_1_max__ = n1;
            for (size_t j_1__ = 0; j_1__ < p01_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(p01(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: p01" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable p01: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "p01", p01, 0);
            check_less_or_equal(function__, "p01", p01, 1);
            current_statement_begin__ = 90;
            size_t p02_j_1_max__ = n2;
            for (size_t j_1__ = 0; j_1__ < p02_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(p02(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: p02" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable p02: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "p02", p02, 0);
            check_less_or_equal(function__, "p02", p02, 1);
            // model body
            {
            current_statement_begin__ = 115;
            validate_non_negative_index("f", "(n2 + 1)", (n2 + 1));
            validate_non_negative_index("f", "(n1 + 1)", (n1 + 1));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> f((n2 + 1), (n1 + 1));
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 116;
            validate_non_negative_index("fobs", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> fobs(N);
            stan::math::initialize(fobs, DUMMY_VAR__);
            stan::math::fill(fobs, DUMMY_VAR__);
            current_statement_begin__ = 117;
            validate_non_negative_index("noise", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> noise(N);
            stan::math::initialize(noise, DUMMY_VAR__);
            stan::math::fill(noise, DUMMY_VAR__);
            current_statement_begin__ = 118;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        1, 
                        "assigning variable f");
            current_statement_begin__ = 119;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_min_max(2, (n1 + 1)), stan::model::nil_index_list())), 
                        p01, 
                        "assigning variable f");
            current_statement_begin__ = 120;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_min_max(2, (n2 + 1)), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        p02, 
                        "assigning variable f");
            current_statement_begin__ = 121;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_min_max(2, (n2 + 1)), stan::model::cons_list(stan::model::index_min_max(2, (n1 + 1)), stan::model::nil_index_list())), 
                        p0, 
                        "assigning variable f");
            current_statement_begin__ = 124;
            lp_accum__.add((cauchy_log(s, 0, 1) - cauchy_ccdf_log(0, 0, 1)));
            current_statement_begin__ = 125;
            lp_accum__.add(inv_gamma_log(s2_log10_ec50_1, 3, 2));
            current_statement_begin__ = 126;
            lp_accum__.add(inv_gamma_log(s2_log10_ec50_2, 3, 2));
            current_statement_begin__ = 130;
            lp_accum__.add(beta_log(la_1, 1, 1.25));
            current_statement_begin__ = 131;
            lp_accum__.add(beta_log(la_2, 1, 1.25));
            current_statement_begin__ = 132;
            lp_accum__.add(gamma_log(slope_1, 1, 1));
            current_statement_begin__ = 133;
            lp_accum__.add(gamma_log(slope_2, 1, 1));
            current_statement_begin__ = 134;
            lp_accum__.add(std_normal_log(theta_1));
            current_statement_begin__ = 135;
            lp_accum__.add(std_normal_log(theta_2));
            current_statement_begin__ = 136;
            lp_accum__.add(normal_log(log10_ec50_1, theta_1, stan::math::sqrt(s2_log10_ec50_1)));
            current_statement_begin__ = 137;
            lp_accum__.add(normal_log(log10_ec50_2, theta_2, stan::math::sqrt(s2_log10_ec50_2)));
            current_statement_begin__ = 140;
            stan::math::assign(fobs, stan::model::rvalue(to_vector(f), stan::model::cons_list(stan::model::index_multi(ii_obs), stan::model::nil_index_list()), "to_vector(f)"));
            current_statement_begin__ = 141;
            stan::math::assign(noise, multiply(s, stan::math::sqrt(add(fobs, lambda))));
            current_statement_begin__ = 142;
            if (as_bool(heteroscedastic)) {
                current_statement_begin__ = 143;
                if (as_bool(robust)) {
                    current_statement_begin__ = 144;
                    for (int n = 1; n <= N; ++n) {
                        current_statement_begin__ = 145;
                        lp_accum__.add((lptn(rho, ((get_base1(y, n, "y", 1) - get_base1(fobs, n, "fobs", 1)) / get_base1(noise, n, "noise", 1)), lambdaLPTN, tauLPTN, pstream__) - stan::math::log(get_base1(noise, n, "noise", 1))));
                    }
                } else {
                    current_statement_begin__ = 148;
                    lp_accum__.add(normal_log(y, fobs, noise));
                }
            } else {
                current_statement_begin__ = 152;
                if (as_bool(robust)) {
                    current_statement_begin__ = 153;
                    for (int n = 1; n <= N; ++n) {
                        current_statement_begin__ = 154;
                        lp_accum__.add((lptn(rho, ((get_base1(y, n, "y", 1) - get_base1(fobs, n, "fobs", 1)) / s), lambdaLPTN, tauLPTN, pstream__) - stan::math::log(s)));
                    }
                } else {
                    current_statement_begin__ = 157;
                    lp_accum__.add(normal_log(y, fobs, s));
                }
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("la_1");
        names__.push_back("la_2");
        names__.push_back("log10_ec50_1");
        names__.push_back("log10_ec50_2");
        names__.push_back("theta_1");
        names__.push_back("theta_2");
        names__.push_back("slope_1");
        names__.push_back("slope_2");
        names__.push_back("s");
        names__.push_back("s2_log10_ec50_1");
        names__.push_back("s2_log10_ec50_2");
        names__.push_back("p0");
        names__.push_back("p01");
        names__.push_back("p02");
        names__.push_back("ec50_1");
        names__.push_back("ec50_2");
        names__.push_back("CPO");
        names__.push_back("dss_1");
        names__.push_back("dss_2");
        names__.push_back("rVUS_f");
        names__.push_back("rVUS_p0");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back((est_la ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((est_la ? 1 : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n2);
        dims__.push_back(n1);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n1);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_nointeraction_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> la_1;
        size_t la_1_d_0_max__ = (est_la ? 1 : 0 );
        la_1.reserve(la_1_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < la_1_d_0_max__; ++d_0__) {
            la_1.push_back(in__.scalar_lub_constrain(0, 1));
        }
        size_t la_1_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_1_k_0_max__; ++k_0__) {
            vars__.push_back(la_1[k_0__]);
        }
        std::vector<double> la_2;
        size_t la_2_d_0_max__ = (est_la ? 1 : 0 );
        la_2.reserve(la_2_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < la_2_d_0_max__; ++d_0__) {
            la_2.push_back(in__.scalar_lub_constrain(0, 1));
        }
        size_t la_2_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_2_k_0_max__; ++k_0__) {
            vars__.push_back(la_2[k_0__]);
        }
        double log10_ec50_1 = in__.scalar_constrain();
        vars__.push_back(log10_ec50_1);
        double log10_ec50_2 = in__.scalar_constrain();
        vars__.push_back(log10_ec50_2);
        double theta_1 = in__.scalar_constrain();
        vars__.push_back(theta_1);
        double theta_2 = in__.scalar_constrain();
        vars__.push_back(theta_2);
        double slope_1 = in__.scalar_lb_constrain(0);
        vars__.push_back(slope_1);
        double slope_2 = in__.scalar_lb_constrain(0);
        vars__.push_back(slope_2);
        double s = in__.scalar_lb_constrain(0);
        vars__.push_back(s);
        double s2_log10_ec50_1 = in__.scalar_lb_constrain(0);
        vars__.push_back(s2_log10_ec50_1);
        double s2_log10_ec50_2 = in__.scalar_lb_constrain(0);
        vars__.push_back(s2_log10_ec50_2);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 88;
            validate_non_negative_index("p0", "n2", n2);
            validate_non_negative_index("p0", "n1", n1);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> p0(n2, n1);
            stan::math::initialize(p0, DUMMY_VAR__);
            stan::math::fill(p0, DUMMY_VAR__);
            current_statement_begin__ = 89;
            validate_non_negative_index("p01", "n1", n1);
            Eigen::Matrix<double, 1, Eigen::Dynamic> p01(n1);
            stan::math::initialize(p01, DUMMY_VAR__);
            stan::math::fill(p01, DUMMY_VAR__);
            current_statement_begin__ = 90;
            validate_non_negative_index("p02", "n2", n2);
            Eigen::Matrix<double, Eigen::Dynamic, 1> p02(n2);
            stan::math::initialize(p02, DUMMY_VAR__);
            stan::math::fill(p02, DUMMY_VAR__);
            // do transformed parameters statements
            {
            current_statement_begin__ = 93;
            local_scalar_t__ la_1_param(DUMMY_VAR__);
            (void) la_1_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_1_param, DUMMY_VAR__);
            stan::math::fill(la_1_param, DUMMY_VAR__);
            current_statement_begin__ = 94;
            local_scalar_t__ la_2_param(DUMMY_VAR__);
            (void) la_2_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_2_param, DUMMY_VAR__);
            stan::math::fill(la_2_param, DUMMY_VAR__);
            current_statement_begin__ = 96;
            if (as_bool(est_la)) {
                current_statement_begin__ = 97;
                stan::math::assign(la_1_param, get_base1(la_1, 1, "la_1", 1));
                current_statement_begin__ = 98;
                stan::math::assign(la_2_param, get_base1(la_2, 1, "la_2", 1));
            } else {
                current_statement_begin__ = 100;
                stan::math::assign(la_1_param, 0);
                current_statement_begin__ = 101;
                stan::math::assign(la_2_param, 0);
            }
            current_statement_begin__ = 104;
            for (int j = 1; j <= n1; ++j) {
                current_statement_begin__ = 105;
                stan::model::assign(p01, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                            (la_1_param + ((1 - la_1_param) / (1 + pow(10, (slope_1 * (get_base1(x1, j, "x1", 1) - log10_ec50_1)))))), 
                            "assigning variable p01");
                current_statement_begin__ = 106;
                for (int i = 1; i <= n2; ++i) {
                    current_statement_begin__ = 107;
                    stan::model::assign(p02, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (la_2_param + ((1 - la_2_param) / (1 + pow(10, (slope_2 * (get_base1(x2, i, "x2", 1) - log10_ec50_2)))))), 
                                "assigning variable p02");
                    current_statement_begin__ = 108;
                    stan::model::assign(p0, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                (get_base1(p01, j, "p01", 1) * get_base1(p02, i, "p02", 1)), 
                                "assigning variable p0");
                }
            }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 88;
            check_greater_or_equal(function__, "p0", p0, 0);
            check_less_or_equal(function__, "p0", p0, 1);
            current_statement_begin__ = 89;
            check_greater_or_equal(function__, "p01", p01, 0);
            check_less_or_equal(function__, "p01", p01, 1);
            current_statement_begin__ = 90;
            check_greater_or_equal(function__, "p02", p02, 0);
            check_less_or_equal(function__, "p02", p02, 1);
            // write transformed parameters
            if (include_tparams__) {
                size_t p0_j_2_max__ = n1;
                size_t p0_j_1_max__ = n2;
                for (size_t j_2__ = 0; j_2__ < p0_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < p0_j_1_max__; ++j_1__) {
                        vars__.push_back(p0(j_1__, j_2__));
                    }
                }
                size_t p01_j_1_max__ = n1;
                for (size_t j_1__ = 0; j_1__ < p01_j_1_max__; ++j_1__) {
                    vars__.push_back(p01(j_1__));
                }
                size_t p02_j_1_max__ = n2;
                for (size_t j_1__ = 0; j_1__ < p02_j_1_max__; ++j_1__) {
                    vars__.push_back(p02(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 164;
            double ec50_1;
            (void) ec50_1;  // dummy to suppress unused var warning
            stan::math::initialize(ec50_1, DUMMY_VAR__);
            stan::math::fill(ec50_1, DUMMY_VAR__);
            current_statement_begin__ = 165;
            double ec50_2;
            (void) ec50_2;  // dummy to suppress unused var warning
            stan::math::initialize(ec50_2, DUMMY_VAR__);
            stan::math::fill(ec50_2, DUMMY_VAR__);
            current_statement_begin__ = 166;
            validate_non_negative_index("CPO", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> CPO(N);
            stan::math::initialize(CPO, DUMMY_VAR__);
            stan::math::fill(CPO, DUMMY_VAR__);
            stan::math::assign(CPO,rep_vector(0, N));
            current_statement_begin__ = 167;
            double dss_1;
            (void) dss_1;  // dummy to suppress unused var warning
            stan::math::initialize(dss_1, DUMMY_VAR__);
            stan::math::fill(dss_1, DUMMY_VAR__);
            stan::math::assign(dss_1,0);
            current_statement_begin__ = 168;
            double dss_2;
            (void) dss_2;  // dummy to suppress unused var warning
            stan::math::initialize(dss_2, DUMMY_VAR__);
            stan::math::fill(dss_2, DUMMY_VAR__);
            stan::math::assign(dss_2,0);
            current_statement_begin__ = 169;
            double rVUS_f;
            (void) rVUS_f;  // dummy to suppress unused var warning
            stan::math::initialize(rVUS_f, DUMMY_VAR__);
            stan::math::fill(rVUS_f, DUMMY_VAR__);
            stan::math::assign(rVUS_f,0);
            current_statement_begin__ = 170;
            double rVUS_p0;
            (void) rVUS_p0;  // dummy to suppress unused var warning
            stan::math::initialize(rVUS_p0, DUMMY_VAR__);
            stan::math::fill(rVUS_p0, DUMMY_VAR__);
            stan::math::assign(rVUS_p0,0);
            // generated quantities statements
            {
            current_statement_begin__ = 173;
            validate_non_negative_index("f", "(n2 + 1)", (n2 + 1));
            validate_non_negative_index("f", "(n1 + 1)", (n1 + 1));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> f((n2 + 1), (n1 + 1));
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 174;
            validate_non_negative_index("fc_interior", "n2", n2);
            validate_non_negative_index("fc_interior", "n1", n1);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> fc_interior(n2, n1);
            stan::math::initialize(fc_interior, DUMMY_VAR__);
            stan::math::fill(fc_interior, DUMMY_VAR__);
            current_statement_begin__ = 175;
            validate_non_negative_index("fobs", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> fobs(N);
            stan::math::initialize(fobs, DUMMY_VAR__);
            stan::math::fill(fobs, DUMMY_VAR__);
            current_statement_begin__ = 176;
            validate_non_negative_index("noise", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> noise(N);
            stan::math::initialize(noise, DUMMY_VAR__);
            stan::math::fill(noise, DUMMY_VAR__);
            current_statement_begin__ = 177;
            local_scalar_t__ la_1_param(DUMMY_VAR__);
            (void) la_1_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_1_param, DUMMY_VAR__);
            stan::math::fill(la_1_param, DUMMY_VAR__);
            current_statement_begin__ = 178;
            local_scalar_t__ la_2_param(DUMMY_VAR__);
            (void) la_2_param;  // dummy to suppress unused var warning
            stan::math::initialize(la_2_param, DUMMY_VAR__);
            stan::math::fill(la_2_param, DUMMY_VAR__);
            current_statement_begin__ = 181;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        1, 
                        "assigning variable f");
            current_statement_begin__ = 182;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_min_max(2, (n1 + 1)), stan::model::nil_index_list())), 
                        p01, 
                        "assigning variable f");
            current_statement_begin__ = 183;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_min_max(2, (n2 + 1)), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        p02, 
                        "assigning variable f");
            current_statement_begin__ = 184;
            stan::model::assign(f, 
                        stan::model::cons_list(stan::model::index_min_max(2, (n2 + 1)), stan::model::cons_list(stan::model::index_min_max(2, (n1 + 1)), stan::model::nil_index_list())), 
                        p0, 
                        "assigning variable f");
            current_statement_begin__ = 185;
            stan::model::assign(fc_interior, 
                        stan::model::cons_list(stan::model::index_min_max(1, n2), stan::model::cons_list(stan::model::index_min_max(1, n1), stan::model::nil_index_list())), 
                        subtract(1, p0), 
                        "assigning variable fc_interior");
            current_statement_begin__ = 189;
            stan::math::assign(fobs, stan::model::rvalue(to_vector(f), stan::model::cons_list(stan::model::index_multi(ii_obs), stan::model::nil_index_list()), "to_vector(f)"));
            current_statement_begin__ = 190;
            stan::math::assign(noise, multiply(s, stan::math::sqrt(add(fobs, lambda))));
            current_statement_begin__ = 191;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 192;
                if (as_bool(heteroscedastic)) {
                    current_statement_begin__ = 193;
                    stan::model::assign(CPO, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                stan::math::exp(-(normal_log(get_base1(y, i, "y", 1), get_base1(fobs, i, "fobs", 1), get_base1(noise, i, "noise", 1)))), 
                                "assigning variable CPO");
                } else {
                    current_statement_begin__ = 195;
                    stan::model::assign(CPO, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                stan::math::exp(-(normal_log(get_base1(y, i, "y", 1), get_base1(fobs, i, "fobs", 1), s))), 
                                "assigning variable CPO");
                }
            }
            current_statement_begin__ = 199;
            stan::math::assign(ec50_1, pow(10, log10_ec50_1));
            current_statement_begin__ = 200;
            stan::math::assign(ec50_2, pow(10, log10_ec50_2));
            current_statement_begin__ = 202;
            if (as_bool(est_la)) {
                current_statement_begin__ = 203;
                stan::math::assign(la_1_param, get_base1(la_1, 1, "la_1", 1));
                current_statement_begin__ = 204;
                stan::math::assign(la_2_param, get_base1(la_2, 1, "la_2", 1));
            } else {
                current_statement_begin__ = 206;
                stan::math::assign(la_1_param, 0);
                current_statement_begin__ = 207;
                stan::math::assign(la_2_param, 0);
            }
            current_statement_begin__ = 210;
            stan::math::assign(dss_1, dss(c11, c12, la_1_param, slope_1, log10_ec50_1, pstream__));
            current_statement_begin__ = 211;
            stan::math::assign(dss_2, dss(c21, c22, la_2_param, slope_2, log10_ec50_2, pstream__));
            current_statement_begin__ = 214;
            stan::math::assign(rVUS_f, VUS(fc_interior, x1, x2, pstream__));
            current_statement_begin__ = 215;
            stan::math::assign(rVUS_p0, VUS(subtract(1, p0), x1, x2, pstream__));
            current_statement_begin__ = 218;
            if (as_bool(logical_eq(rVUS_f, 0))) {
                current_statement_begin__ = 218;
                stan::math::assign(rVUS_f, uniform_rng(1e-6, 1e-4, base_rng__));
            }
            current_statement_begin__ = 219;
            if (as_bool(logical_eq(rVUS_p0, 0))) {
                current_statement_begin__ = 219;
                stan::math::assign(rVUS_p0, uniform_rng(1e-6, 1e-4, base_rng__));
            }
            }
            // validate, write generated quantities
            current_statement_begin__ = 164;
            vars__.push_back(ec50_1);
            current_statement_begin__ = 165;
            vars__.push_back(ec50_2);
            current_statement_begin__ = 166;
            size_t CPO_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < CPO_j_1_max__; ++j_1__) {
                vars__.push_back(CPO(j_1__));
            }
            current_statement_begin__ = 167;
            vars__.push_back(dss_1);
            current_statement_begin__ = 168;
            vars__.push_back(dss_2);
            current_statement_begin__ = 169;
            vars__.push_back(rVUS_f);
            current_statement_begin__ = 170;
            vars__.push_back(rVUS_p0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_nointeraction";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t la_1_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_1_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "la_1" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t la_2_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "la_2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "log10_ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "log10_ec50_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2_log10_ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2_log10_ec50_2";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t p0_j_2_max__ = n1;
            size_t p0_j_1_max__ = n2;
            for (size_t j_2__ = 0; j_2__ < p0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < p0_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p0" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t p01_j_1_max__ = n1;
            for (size_t j_1__ = 0; j_1__ < p01_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p01" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t p02_j_1_max__ = n2;
            for (size_t j_1__ = 0; j_1__ < p02_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p02" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ec50_2";
        param_names__.push_back(param_name_stream__.str());
        size_t CPO_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < CPO_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "CPO" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dss_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "dss_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rVUS_f";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rVUS_p0";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t la_1_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_1_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "la_1" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t la_2_k_0_max__ = (est_la ? 1 : 0 );
        for (size_t k_0__ = 0; k_0__ < la_2_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "la_2" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "log10_ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "log10_ec50_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "slope_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2_log10_ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2_log10_ec50_2";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t p0_j_2_max__ = n1;
            size_t p0_j_1_max__ = n2;
            for (size_t j_2__ = 0; j_2__ < p0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < p0_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "p0" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t p01_j_1_max__ = n1;
            for (size_t j_1__ = 0; j_1__ < p01_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p01" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t p02_j_1_max__ = n2;
            for (size_t j_1__ = 0; j_1__ < p02_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p02" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "ec50_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ec50_2";
        param_names__.push_back(param_name_stream__.str());
        size_t CPO_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < CPO_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "CPO" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "dss_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "dss_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rVUS_f";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rVUS_p0";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_nointeraction_namespace::model_nointeraction stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
