// Generated by rstantools.  Do not edit by hand.

/*
    BayesIntComp is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BayesIntComp is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BayesIntComp.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-1-g67504470
#include <stan/model/model_header.hpp>
namespace model_nointeraction_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'nointeraction', line 40, column 2 to column 45)",
                                                      " (in 'nointeraction', line 41, column 2 to column 45)",
                                                      " (in 'nointeraction', line 42, column 2 to column 20)",
                                                      " (in 'nointeraction', line 43, column 2 to column 20)",
                                                      " (in 'nointeraction', line 44, column 2 to column 15)",
                                                      " (in 'nointeraction', line 45, column 2 to column 15)",
                                                      " (in 'nointeraction', line 46, column 2 to column 24)",
                                                      " (in 'nointeraction', line 47, column 2 to column 24)",
                                                      " (in 'nointeraction', line 49, column 2 to column 18)",
                                                      " (in 'nointeraction', line 50, column 2 to column 32)",
                                                      " (in 'nointeraction', line 51, column 2 to column 32)",
                                                      " (in 'nointeraction', line 54, column 2 to column 37)",
                                                      " (in 'nointeraction', line 55, column 2 to column 39)",
                                                      " (in 'nointeraction', line 56, column 2 to column 35)",
                                                      " (in 'nointeraction', line 58, column 4 to column 20)",
                                                      " (in 'nointeraction', line 59, column 4 to column 20)",
                                                      " (in 'nointeraction', line 64, column 6 to column 21)",
                                                      " (in 'nointeraction', line 65, column 6 to column 21)",
                                                      " (in 'nointeraction', line 63, column 11 to line 66, column 5)",
                                                      " (in 'nointeraction', line 61, column 6 to column 27)",
                                                      " (in 'nointeraction', line 62, column 6 to column 27)",
                                                      " (in 'nointeraction', line 60, column 15 to line 63, column 5)",
                                                      " (in 'nointeraction', line 60, column 4 to line 66, column 5)",
                                                      " (in 'nointeraction', line 68, column 6 to column 79)",
                                                      " (in 'nointeraction', line 70, column 8 to column 81)",
                                                      " (in 'nointeraction', line 71, column 8 to column 32)",
                                                      " (in 'nointeraction', line 69, column 21 to line 72, column 7)",
                                                      " (in 'nointeraction', line 69, column 6 to line 72, column 7)",
                                                      " (in 'nointeraction', line 67, column 19 to line 73, column 5)",
                                                      " (in 'nointeraction', line 67, column 4 to line 73, column 5)",
                                                      " (in 'nointeraction', line 57, column 2 to line 74, column 3)",
                                                      " (in 'nointeraction', line 120, column 2 to column 14)",
                                                      " (in 'nointeraction', line 121, column 2 to column 14)",
                                                      " (in 'nointeraction', line 122, column 2 to column 34)",
                                                      " (in 'nointeraction', line 123, column 2 to column 17)",
                                                      " (in 'nointeraction', line 124, column 2 to column 17)",
                                                      " (in 'nointeraction', line 125, column 2 to column 18)",
                                                      " (in 'nointeraction', line 126, column 2 to column 19)",
                                                      " (in 'nointeraction', line 128, column 11 to column 15)",
                                                      " (in 'nointeraction', line 128, column 16 to column 20)",
                                                      " (in 'nointeraction', line 128, column 4 to column 24)",
                                                      " (in 'nointeraction', line 129, column 11 to column 13)",
                                                      " (in 'nointeraction', line 129, column 14 to column 16)",
                                                      " (in 'nointeraction', line 129, column 4 to column 30)",
                                                      " (in 'nointeraction', line 130, column 11 to column 12)",
                                                      " (in 'nointeraction', line 130, column 4 to column 19)",
                                                      " (in 'nointeraction', line 131, column 11 to column 12)",
                                                      " (in 'nointeraction', line 131, column 4 to column 20)",
                                                      " (in 'nointeraction', line 132, column 4 to column 20)",
                                                      " (in 'nointeraction', line 133, column 4 to column 20)",
                                                      " (in 'nointeraction', line 134, column 4 to column 23)",
                                                      " (in 'nointeraction', line 135, column 4 to column 23)",
                                                      " (in 'nointeraction', line 136, column 4 to column 23)",
                                                      " (in 'nointeraction', line 137, column 4 to column 23)",
                                                      " (in 'nointeraction', line 138, column 11 to column 13)",
                                                      " (in 'nointeraction', line 138, column 4 to column 22)",
                                                      " (in 'nointeraction', line 139, column 11 to column 13)",
                                                      " (in 'nointeraction', line 139, column 4 to column 25)",
                                                      " (in 'nointeraction', line 141, column 4 to column 15)",
                                                      " (in 'nointeraction', line 142, column 4 to column 24)",
                                                      " (in 'nointeraction', line 143, column 4 to column 24)",
                                                      " (in 'nointeraction', line 144, column 4 to column 30)",
                                                      " (in 'nointeraction', line 145, column 4 to column 38)",
                                                      " (in 'nointeraction', line 147, column 4 to column 32)",
                                                      " (in 'nointeraction', line 148, column 4 to column 34)",
                                                      " (in 'nointeraction', line 153, column 8 to column 54)",
                                                      " (in 'nointeraction', line 152, column 13 to line 154, column 7)",
                                                      " (in 'nointeraction', line 151, column 8 to column 61)",
                                                      " (in 'nointeraction', line 150, column 26 to line 152, column 7)",
                                                      " (in 'nointeraction', line 150, column 6 to line 154, column 7)",
                                                      " (in 'nointeraction', line 149, column 18 to line 155, column 5)",
                                                      " (in 'nointeraction', line 149, column 4 to line 155, column 5)",
                                                      " (in 'nointeraction', line 157, column 4 to column 29)",
                                                      " (in 'nointeraction', line 158, column 4 to column 29)",
                                                      " (in 'nointeraction', line 164, column 6 to column 21)",
                                                      " (in 'nointeraction', line 165, column 6 to column 21)",
                                                      " (in 'nointeraction', line 163, column 11 to line 166, column 5)",
                                                      " (in 'nointeraction', line 161, column 6 to column 27)",
                                                      " (in 'nointeraction', line 162, column 6 to column 27)",
                                                      " (in 'nointeraction', line 160, column 15 to line 163, column 5)",
                                                      " (in 'nointeraction', line 160, column 4 to line 166, column 5)",
                                                      " (in 'nointeraction', line 167, column 4 to column 131)",
                                                      " (in 'nointeraction', line 168, column 4 to column 38)",
                                                      " (in 'nointeraction', line 169, column 4 to column 131)",
                                                      " (in 'nointeraction', line 170, column 4 to column 38)",
                                                      " (in 'nointeraction', line 173, column 6 to column 22)",
                                                      " (in 'nointeraction', line 174, column 6 to column 25)",
                                                      " (in 'nointeraction', line 176, column 8 to column 78)",
                                                      " (in 'nointeraction', line 177, column 8 to column 71)",
                                                      " (in 'nointeraction', line 175, column 21 to line 178, column 7)",
                                                      " (in 'nointeraction', line 175, column 6 to line 178, column 7)",
                                                      " (in 'nointeraction', line 179, column 6 to column 25)",
                                                      " (in 'nointeraction', line 180, column 6 to column 31)",
                                                      " (in 'nointeraction', line 182, column 8 to column 66)",
                                                      " (in 'nointeraction', line 183, column 8 to column 73)",
                                                      " (in 'nointeraction', line 181, column 16 to line 184, column 7)",
                                                      " (in 'nointeraction', line 181, column 6 to line 184, column 7)",
                                                      " (in 'nointeraction', line 172, column 19 to line 185, column 5)",
                                                      " (in 'nointeraction', line 172, column 4 to line 185, column 5)",
                                                      " (in 'nointeraction', line 187, column 4 to column 66)",
                                                      " (in 'nointeraction', line 188, column 4 to column 68)",
                                                      " (in 'nointeraction', line 190, column 21 to column 53)",
                                                      " (in 'nointeraction', line 190, column 20 to column 54)",
                                                      " (in 'nointeraction', line 190, column 4 to column 54)",
                                                      " (in 'nointeraction', line 191, column 22 to column 55)",
                                                      " (in 'nointeraction', line 191, column 21 to column 56)",
                                                      " (in 'nointeraction', line 191, column 4 to column 56)",
                                                      " (in 'nointeraction', line 127, column 2 to line 192, column 3)",
                                                      " (in 'nointeraction', line 78, column 9 to column 13)",
                                                      " (in 'nointeraction', line 78, column 14 to column 18)",
                                                      " (in 'nointeraction', line 78, column 2 to column 22)",
                                                      " (in 'nointeraction', line 79, column 9 to column 10)",
                                                      " (in 'nointeraction', line 79, column 2 to column 17)",
                                                      " (in 'nointeraction', line 80, column 9 to column 10)",
                                                      " (in 'nointeraction', line 80, column 2 to column 18)",
                                                      " (in 'nointeraction', line 81, column 2 to column 13)",
                                                      " (in 'nointeraction', line 82, column 2 to column 22)",
                                                      " (in 'nointeraction', line 83, column 2 to column 22)",
                                                      " (in 'nointeraction', line 84, column 2 to column 28)",
                                                      " (in 'nointeraction', line 86, column 2 to column 34)",
                                                      " (in 'nointeraction', line 87, column 2 to column 50)",
                                                      " (in 'nointeraction', line 88, column 2 to column 50)",
                                                      " (in 'nointeraction', line 90, column 2 to column 37)",
                                                      " (in 'nointeraction', line 91, column 2 to column 37)",
                                                      " (in 'nointeraction', line 92, column 2 to column 38)",
                                                      " (in 'nointeraction', line 93, column 2 to column 38)",
                                                      " (in 'nointeraction', line 94, column 2 to column 37)",
                                                      " (in 'nointeraction', line 95, column 2 to column 37)",
                                                      " (in 'nointeraction', line 96, column 2 to column 70)",
                                                      " (in 'nointeraction', line 97, column 2 to column 70)",
                                                      " (in 'nointeraction', line 99, column 2 to column 30)",
                                                      " (in 'nointeraction', line 100, column 2 to column 32)",
                                                      " (in 'nointeraction', line 115, column 6 to column 40)",
                                                      " (in 'nointeraction', line 114, column 10 to line 116, column 5)",
                                                      " (in 'nointeraction', line 112, column 8 to column 73)",
                                                      " (in 'nointeraction', line 111, column 21 to line 113, column 7)",
                                                      " (in 'nointeraction', line 111, column 6 to line 113, column 7)",
                                                      " (in 'nointeraction', line 110, column 15 to line 114, column 5)",
                                                      " (in 'nointeraction', line 110, column 4 to line 116, column 5)",
                                                      " (in 'nointeraction', line 109, column 8 to line 117, column 3)",
                                                      " (in 'nointeraction', line 107, column 6 to column 44)",
                                                      " (in 'nointeraction', line 106, column 10 to line 108, column 5)",
                                                      " (in 'nointeraction', line 104, column 8 to column 87)",
                                                      " (in 'nointeraction', line 103, column 21 to line 105, column 7)",
                                                      " (in 'nointeraction', line 103, column 6 to line 105, column 7)",
                                                      " (in 'nointeraction', line 102, column 15 to line 106, column 5)",
                                                      " (in 'nointeraction', line 102, column 4 to line 108, column 5)",
                                                      " (in 'nointeraction', line 101, column 22 to line 109, column 3)",
                                                      " (in 'nointeraction', line 101, column 2 to line 117, column 3)",
                                                      " (in 'nointeraction', line 17, column 2 to column 18)",
                                                      " (in 'nointeraction', line 18, column 2 to column 18)",
                                                      " (in 'nointeraction', line 19, column 2 to column 24)",
                                                      " (in 'nointeraction', line 20, column 2 to column 20)",
                                                      " (in 'nointeraction', line 21, column 9 to column 38)",
                                                      " (in 'nointeraction', line 21, column 2 to column 42)",
                                                      " (in 'nointeraction', line 22, column 13 to column 42)",
                                                      " (in 'nointeraction', line 22, column 2 to column 44)",
                                                      " (in 'nointeraction', line 23, column 10 to column 12)",
                                                      " (in 'nointeraction', line 23, column 2 to column 14)",
                                                      " (in 'nointeraction', line 24, column 10 to column 12)",
                                                      " (in 'nointeraction', line 24, column 2 to column 14)",
                                                      " (in 'nointeraction', line 25, column 2 to column 13)",
                                                      " (in 'nointeraction', line 26, column 2 to column 22)",
                                                      " (in 'nointeraction', line 27, column 2 to column 13)",
                                                      " (in 'nointeraction', line 28, column 2 to column 14)",
                                                      " (in 'nointeraction', line 29, column 2 to column 27)",
                                                      " (in 'nointeraction', line 30, column 2 to column 11)",
                                                      " (in 'nointeraction', line 31, column 2 to column 14)",
                                                      " (in 'nointeraction', line 34, column 2 to column 40)",
                                                      " (in 'nointeraction', line 35, column 2 to column 36)",
                                                      " (in 'nointeraction', line 36, column 2 to column 86)",
                                                      " (in 'nointeraction', line 40, column 29 to column 43)",
                                                      " (in 'nointeraction', line 41, column 29 to column 43)",
                                                      " (in 'nointeraction', line 54, column 27 to column 29)",
                                                      " (in 'nointeraction', line 54, column 30 to column 32)",
                                                      " (in 'nointeraction', line 55, column 31 to column 33)",
                                                      " (in 'nointeraction', line 56, column 27 to column 29)",
                                                      " (in 'nointeraction', line 122, column 9 to column 10)",
                                                      " (in 'nointeraction', line 8, column 6 to column 27)",
                                                      " (in 'nointeraction', line 9, column 6 to column 30)",
                                                      " (in 'nointeraction', line 10, column 6 to column 34)",
                                                      " (in 'nointeraction', line 11, column 6 to column 90)",
                                                      " (in 'nointeraction', line 12, column 6 to column 18)",
                                                      " (in 'nointeraction', line 7, column 9 to line 13, column 5)",
                                                      " (in 'nointeraction', line 5, column 6 to column 35)",
                                                      " (in 'nointeraction', line 4, column 23 to line 6, column 5)",
                                                      " (in 'nointeraction', line 4, column 4 to line 13, column 5)",
                                                      " (in 'nointeraction', line 3, column 52 to line 14, column 3)"};
template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, T2__,
T3__>
lptn(const T0__& rho, const T1__& z, const T2__& lambda, const T3__& tau,
     std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 187;
    if (logical_lte(stan::math::fabs(z), tau)) {
      current_statement__ = 185;
      return normal_lpdf<false>(z, 0, 1);
    } else {
      local_scalar_t__ logt;
      logt = DUMMY_VAR__;
      
      current_statement__ = 179;
      logt = stan::math::log(tau);
      local_scalar_t__ logl;
      logl = DUMMY_VAR__;
      
      current_statement__ = 180;
      logl = stan::math::log(lambda);
      local_scalar_t__ logabsz;
      logabsz = DUMMY_VAR__;
      
      current_statement__ = 181;
      logabsz = stan::math::log(stan::math::fabs(z));
      local_scalar_t__ lpdf;
      lpdf = DUMMY_VAR__;
      
      current_statement__ = 182;
      lpdf = (((normal_lpdf<false>(tau, 0, 1) + logt) - logabsz) +
               ((lambda + 1) * stan::math::log((logt / logabsz))));
      current_statement__ = 183;
      return lpdf;
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct lptn_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, T2__,
T3__>
operator()(const T0__& rho, const T1__& z, const T2__& lambda,
           const T3__& tau, std::ostream* pstream__)  const 
{
return lptn(rho, z, lambda, tau, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_nointeraction final : public model_base_crtp<model_nointeraction> {
private:
  int n1;
  int n2;
  int nmissing;
  int nrep;
  Eigen::Matrix<double, -1, 1> y;
  std::vector<int> ii_obs;
  std::vector<double> x1;
  std::vector<double> x2;
  int est_la;
  int heteroscedastic;
  int robust;
  int pcprior;
  Eigen::Matrix<double, -1, 1> pcprior_hypers;
  double rho;
  double lambda;
  int N;
  double tauLPTN;
  double lambdaLPTN;
  int la_1_1dim__;
  int la_2_1dim__;
 
public:
  ~model_nointeraction() { }
  
  inline std::string model_name() const final { return "model_nointeraction"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-1-g67504470", "stancflags = "};
  }
  
  
  model_nointeraction(stan::io::var_context& context__,
                      unsigned int random_seed__ = 0,
                      std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_nointeraction_namespace::model_nointeraction";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 150;
      context__.validate_dims("data initialization","n1","int",
          context__.to_vec());
      n1 = std::numeric_limits<int>::min();
      
      current_statement__ = 150;
      n1 = context__.vals_i("n1")[(1 - 1)];
      current_statement__ = 150;
      current_statement__ = 150;
      check_greater_or_equal(function__, "n1", n1, 1);
      current_statement__ = 151;
      context__.validate_dims("data initialization","n2","int",
          context__.to_vec());
      n2 = std::numeric_limits<int>::min();
      
      current_statement__ = 151;
      n2 = context__.vals_i("n2")[(1 - 1)];
      current_statement__ = 151;
      current_statement__ = 151;
      check_greater_or_equal(function__, "n2", n2, 1);
      current_statement__ = 152;
      context__.validate_dims("data initialization","nmissing","int",
          context__.to_vec());
      nmissing = std::numeric_limits<int>::min();
      
      current_statement__ = 152;
      nmissing = context__.vals_i("nmissing")[(1 - 1)];
      current_statement__ = 152;
      current_statement__ = 152;
      check_greater_or_equal(function__, "nmissing", nmissing, 0);
      current_statement__ = 153;
      context__.validate_dims("data initialization","nrep","int",
          context__.to_vec());
      nrep = std::numeric_limits<int>::min();
      
      current_statement__ = 153;
      nrep = context__.vals_i("nrep")[(1 - 1)];
      current_statement__ = 153;
      current_statement__ = 153;
      check_greater_or_equal(function__, "nrep", nrep, 1);
      current_statement__ = 154;
      validate_non_negative_index("y",
                                  "(n1 + n2 + n1 * n2 + 1) * nrep - nmissing",
                                  (((((n1 + n2) + (n1 * n2)) + 1) * nrep) -
                                    nmissing));
      current_statement__ = 155;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(
            (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)));
      y = Eigen::Matrix<double, -1, 1>((((((n1 + n2) + (n1 * n2)) + 1) *
                                          nrep) - nmissing));
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 155;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 155;
        pos__ = 1;
        current_statement__ = 155;
        for (int sym1__ = 1;
             sym1__ <= (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing);
             ++sym1__) {
          current_statement__ = 155;
          assign(y, cons_list(index_uni(sym1__), nil_index_list()),
            y_flat__[(pos__ - 1)], "assigning variable y");
          current_statement__ = 155;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 156;
      validate_non_negative_index("ii_obs",
                                  "(n1 + n2 + n1 * n2 + 1) * nrep - nmissing",
                                  (((((n1 + n2) + (n1 * n2)) + 1) * nrep) -
                                    nmissing));
      current_statement__ = 157;
      context__.validate_dims("data initialization","ii_obs","int",
          context__.to_vec(
            (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing)));
      ii_obs = std::vector<int>((((((n1 + n2) + (n1 * n2)) + 1) * nrep) -
                                  nmissing), std::numeric_limits<int>::min());
      
      current_statement__ = 157;
      assign(ii_obs, nil_index_list(), context__.vals_i("ii_obs"),
        "assigning variable ii_obs");
      current_statement__ = 158;
      validate_non_negative_index("x1", "n1", n1);
      current_statement__ = 159;
      context__.validate_dims("data initialization","x1","double",
          context__.to_vec(n1));
      x1 = std::vector<double>(n1, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 159;
      assign(x1, nil_index_list(), context__.vals_r("x1"),
        "assigning variable x1");
      current_statement__ = 160;
      validate_non_negative_index("x2", "n2", n2);
      current_statement__ = 161;
      context__.validate_dims("data initialization","x2","double",
          context__.to_vec(n2));
      x2 = std::vector<double>(n2, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 161;
      assign(x2, nil_index_list(), context__.vals_r("x2"),
        "assigning variable x2");
      current_statement__ = 162;
      context__.validate_dims("data initialization","est_la","int",
          context__.to_vec());
      est_la = std::numeric_limits<int>::min();
      
      current_statement__ = 162;
      est_la = context__.vals_i("est_la")[(1 - 1)];
      current_statement__ = 163;
      context__.validate_dims("data initialization","heteroscedastic","int",
          context__.to_vec());
      heteroscedastic = std::numeric_limits<int>::min();
      
      current_statement__ = 163;
      heteroscedastic = context__.vals_i("heteroscedastic")[(1 - 1)];
      current_statement__ = 164;
      context__.validate_dims("data initialization","robust","int",
          context__.to_vec());
      robust = std::numeric_limits<int>::min();
      
      current_statement__ = 164;
      robust = context__.vals_i("robust")[(1 - 1)];
      current_statement__ = 165;
      context__.validate_dims("data initialization","pcprior","int",
          context__.to_vec());
      pcprior = std::numeric_limits<int>::min();
      
      current_statement__ = 165;
      pcprior = context__.vals_i("pcprior")[(1 - 1)];
      current_statement__ = 166;
      context__.validate_dims("data initialization","pcprior_hypers",
          "double",context__.to_vec(4));
      pcprior_hypers = Eigen::Matrix<double, -1, 1>(4);
      stan::math::fill(pcprior_hypers, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> pcprior_hypers_flat__;
        current_statement__ = 166;
        assign(pcprior_hypers_flat__, nil_index_list(),
          context__.vals_r("pcprior_hypers"),
          "assigning variable pcprior_hypers_flat__");
        current_statement__ = 166;
        pos__ = 1;
        current_statement__ = 166;
        for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
          current_statement__ = 166;
          assign(pcprior_hypers,
            cons_list(index_uni(sym1__), nil_index_list()),
            pcprior_hypers_flat__[(pos__ - 1)],
            "assigning variable pcprior_hypers");
          current_statement__ = 166;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 167;
      context__.validate_dims("data initialization","rho","double",
          context__.to_vec());
      rho = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 167;
      rho = context__.vals_r("rho")[(1 - 1)];
      current_statement__ = 168;
      context__.validate_dims("data initialization","lambda","double",
          context__.to_vec());
      lambda = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 168;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      current_statement__ = 169;
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 169;
      N = (((((n1 + n2) + (n1 * n2)) + 1) * nrep) - nmissing);
      current_statement__ = 170;
      tauLPTN = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 170;
      tauLPTN = inv_Phi(((1 + rho) / 2));
      current_statement__ = 171;
      lambdaLPTN = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 171;
      lambdaLPTN = ((((2 * inv((1 - rho))) *
                       stan::math::exp(normal_lpdf<false>(tauLPTN, 0, 1))) *
                      tauLPTN) * stan::math::log(tauLPTN));
      current_statement__ = 172;
      la_1_1dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 172;
      la_1_1dim__ = (est_la ? 1 : 0);
      current_statement__ = 172;
      validate_non_negative_index("la_1", "est_la ? 1 : 0", la_1_1dim__);
      current_statement__ = 173;
      la_2_1dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 173;
      la_2_1dim__ = (est_la ? 1 : 0);
      current_statement__ = 173;
      validate_non_negative_index("la_2", "est_la ? 1 : 0", la_2_1dim__);
      current_statement__ = 174;
      validate_non_negative_index("p0", "n2", n2);
      current_statement__ = 175;
      validate_non_negative_index("p0", "n1", n1);
      current_statement__ = 176;
      validate_non_negative_index("p01", "n1", n1);
      current_statement__ = 177;
      validate_non_negative_index("p02", "n2", n2);
      current_statement__ = 178;
      validate_non_negative_index("CPO", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += la_1_1dim__;
      num_params_r__ += la_2_1dim__;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_nointeraction_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<local_scalar_t__> la_1;
      la_1 = std::vector<local_scalar_t__>(la_1_1dim__, DUMMY_VAR__);
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        current_statement__ = 1;
        assign(la_1, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable la_1");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        current_statement__ = 1;
        if (jacobian__) {
          current_statement__ = 1;
          assign(la_1, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(la_1[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable la_1");
        } else {
          current_statement__ = 1;
          assign(la_1, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(la_1[(sym1__ - 1)], 0, 1),
            "assigning variable la_1");
        }}
      std::vector<local_scalar_t__> la_2;
      la_2 = std::vector<local_scalar_t__>(la_2_1dim__, DUMMY_VAR__);
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        current_statement__ = 2;
        assign(la_2, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable la_2");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(la_2, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(la_2[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable la_2");
        } else {
          current_statement__ = 2;
          assign(la_2, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(la_2[(sym1__ - 1)], 0, 1),
            "assigning variable la_2");
        }}
      local_scalar_t__ log10_ec50_1;
      log10_ec50_1 = DUMMY_VAR__;
      
      current_statement__ = 3;
      log10_ec50_1 = in__.scalar();
      local_scalar_t__ log10_ec50_2;
      log10_ec50_2 = DUMMY_VAR__;
      
      current_statement__ = 4;
      log10_ec50_2 = in__.scalar();
      local_scalar_t__ theta_1;
      theta_1 = DUMMY_VAR__;
      
      current_statement__ = 5;
      theta_1 = in__.scalar();
      local_scalar_t__ theta_2;
      theta_2 = DUMMY_VAR__;
      
      current_statement__ = 6;
      theta_2 = in__.scalar();
      local_scalar_t__ slope_1;
      slope_1 = DUMMY_VAR__;
      
      current_statement__ = 7;
      slope_1 = in__.scalar();
      current_statement__ = 7;
      if (jacobian__) {
        current_statement__ = 7;
        slope_1 = stan::math::lb_constrain(slope_1, 0, lp__);
      } else {
        current_statement__ = 7;
        slope_1 = stan::math::lb_constrain(slope_1, 0);
      }
      local_scalar_t__ slope_2;
      slope_2 = DUMMY_VAR__;
      
      current_statement__ = 8;
      slope_2 = in__.scalar();
      current_statement__ = 8;
      if (jacobian__) {
        current_statement__ = 8;
        slope_2 = stan::math::lb_constrain(slope_2, 0, lp__);
      } else {
        current_statement__ = 8;
        slope_2 = stan::math::lb_constrain(slope_2, 0);
      }
      local_scalar_t__ s;
      s = DUMMY_VAR__;
      
      current_statement__ = 9;
      s = in__.scalar();
      current_statement__ = 9;
      if (jacobian__) {
        current_statement__ = 9;
        s = stan::math::lb_constrain(s, 0, lp__);
      } else {
        current_statement__ = 9;
        s = stan::math::lb_constrain(s, 0);
      }
      local_scalar_t__ s2_log10_ec50_1;
      s2_log10_ec50_1 = DUMMY_VAR__;
      
      current_statement__ = 10;
      s2_log10_ec50_1 = in__.scalar();
      current_statement__ = 10;
      if (jacobian__) {
        current_statement__ = 10;
        s2_log10_ec50_1 = stan::math::lb_constrain(s2_log10_ec50_1, 0, lp__);
      } else {
        current_statement__ = 10;
        s2_log10_ec50_1 = stan::math::lb_constrain(s2_log10_ec50_1, 0);
      }
      local_scalar_t__ s2_log10_ec50_2;
      s2_log10_ec50_2 = DUMMY_VAR__;
      
      current_statement__ = 11;
      s2_log10_ec50_2 = in__.scalar();
      current_statement__ = 11;
      if (jacobian__) {
        current_statement__ = 11;
        s2_log10_ec50_2 = stan::math::lb_constrain(s2_log10_ec50_2, 0, lp__);
      } else {
        current_statement__ = 11;
        s2_log10_ec50_2 = stan::math::lb_constrain(s2_log10_ec50_2, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, -1> p0;
      p0 = Eigen::Matrix<local_scalar_t__, -1, -1>(n2, n1);
      stan::math::fill(p0, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, 1, -1> p01;
      p01 = Eigen::Matrix<local_scalar_t__, 1, -1>(n1);
      stan::math::fill(p01, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> p02;
      p02 = Eigen::Matrix<local_scalar_t__, -1, 1>(n2);
      stan::math::fill(p02, DUMMY_VAR__);
      
      {
        local_scalar_t__ la_1_param;
        la_1_param = DUMMY_VAR__;
        
        local_scalar_t__ la_2_param;
        la_2_param = DUMMY_VAR__;
        
        current_statement__ = 23;
        if (est_la) {
          current_statement__ = 20;
          la_1_param = la_1[(1 - 1)];
          current_statement__ = 21;
          la_2_param = la_2[(1 - 1)];
        } else {
          current_statement__ = 17;
          la_1_param = 0;
          current_statement__ = 18;
          la_2_param = 0;
        }
        current_statement__ = 30;
        for (int j = 1; j <= n1; ++j) {
          current_statement__ = 24;
          assign(p01, cons_list(index_uni(j), nil_index_list()),
            (la_1_param +
              ((1 - la_1_param) /
                (1 + pow(10, (slope_1 * (x1[(j - 1)] - log10_ec50_1)))))),
            "assigning variable p01");
          current_statement__ = 28;
          for (int i = 1; i <= n2; ++i) {
            current_statement__ = 25;
            assign(p02, cons_list(index_uni(i), nil_index_list()),
              (la_2_param +
                ((1 - la_2_param) /
                  (1 + pow(10, (slope_2 * (x2[(i - 1)] - log10_ec50_2)))))),
              "assigning variable p02");
            current_statement__ = 26;
            assign(p0,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              (p01[(j - 1)] * p02[(i - 1)]), "assigning variable p0");}}
      }
      current_statement__ = 12;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 12;
        for (int sym2__ = 1; sym2__ <= n1; ++sym2__) {
          current_statement__ = 12;
          current_statement__ = 12;
          check_greater_or_equal(function__, "p0[sym1__, sym2__]",
                                 rvalue(p0,
                                   cons_list(index_uni(sym1__),
                                     cons_list(index_uni(sym2__),
                                       nil_index_list())), "p0"), 0);}}
      current_statement__ = 12;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 12;
        for (int sym2__ = 1; sym2__ <= n1; ++sym2__) {
          current_statement__ = 12;
          current_statement__ = 12;
          check_less_or_equal(function__, "p0[sym1__, sym2__]",
                              rvalue(p0,
                                cons_list(index_uni(sym1__),
                                  cons_list(index_uni(sym2__),
                                    nil_index_list())), "p0"), 1);}}
      current_statement__ = 13;
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        current_statement__ = 13;
        current_statement__ = 13;
        check_greater_or_equal(function__, "p01[sym1__]", p01[(sym1__ - 1)],
                               0);}
      current_statement__ = 13;
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        current_statement__ = 13;
        current_statement__ = 13;
        check_less_or_equal(function__, "p01[sym1__]", p01[(sym1__ - 1)], 1);
      }
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_greater_or_equal(function__, "p02[sym1__]", p02[(sym1__ - 1)],
                               0);}
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_less_or_equal(function__, "p02[sym1__]", p02[(sym1__ - 1)], 1);
      }
      {
        current_statement__ = 109;
        validate_non_negative_index("f", "n2 + 1", (n2 + 1));
        current_statement__ = 110;
        validate_non_negative_index("f", "n1 + 1", (n1 + 1));
        Eigen::Matrix<local_scalar_t__, -1, -1> f;
        f = Eigen::Matrix<local_scalar_t__, -1, -1>((n2 + 1), (n1 + 1));
        stan::math::fill(f, DUMMY_VAR__);
        
        current_statement__ = 112;
        validate_non_negative_index("fobs", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> fobs;
        fobs = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
        stan::math::fill(fobs, DUMMY_VAR__);
        
        current_statement__ = 114;
        validate_non_negative_index("noise", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> noise;
        noise = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
        stan::math::fill(noise, DUMMY_VAR__);
        
        current_statement__ = 116;
        assign(f,
          cons_list(index_uni(1), cons_list(index_uni(1), nil_index_list())),
          1, "assigning variable f");
        current_statement__ = 117;
        assign(f,
          cons_list(index_uni(1),
            cons_list(index_min_max(2, (n1 + 1)), nil_index_list())), p01,
          "assigning variable f");
        current_statement__ = 118;
        assign(f,
          cons_list(index_min_max(2, (n2 + 1)),
            cons_list(index_uni(1), nil_index_list())), p02,
          "assigning variable f");
        current_statement__ = 119;
        assign(f,
          cons_list(index_min_max(2, (n2 + 1)),
            cons_list(index_min_max(2, (n1 + 1)), nil_index_list())), p0,
          "assigning variable f");
        current_statement__ = 120;
        lp_accum__.add(cauchy_lpdf<false>(s, 0, 1));
        current_statement__ = 121;
        lp_accum__.add(inv_gamma_lpdf<false>(s2_log10_ec50_1, 3, 2));
        current_statement__ = 122;
        lp_accum__.add(inv_gamma_lpdf<false>(s2_log10_ec50_2, 3, 2));
        current_statement__ = 123;
        lp_accum__.add(beta_lpdf<false>(la_1, 1, 1.25));
        current_statement__ = 124;
        lp_accum__.add(beta_lpdf<false>(la_2, 1, 1.25));
        current_statement__ = 125;
        lp_accum__.add(gamma_lpdf<false>(slope_1, 1, 1));
        current_statement__ = 126;
        lp_accum__.add(gamma_lpdf<false>(slope_2, 1, 1));
        current_statement__ = 127;
        lp_accum__.add(std_normal_lpdf<false>(theta_1));
        current_statement__ = 128;
        lp_accum__.add(std_normal_lpdf<false>(theta_2));
        current_statement__ = 129;
        lp_accum__.add(
          normal_lpdf<false>(log10_ec50_1, theta_1,
            stan::math::sqrt(s2_log10_ec50_1)));
        current_statement__ = 130;
        lp_accum__.add(
          normal_lpdf<false>(log10_ec50_2, theta_2,
            stan::math::sqrt(s2_log10_ec50_2)));
        current_statement__ = 131;
        assign(fobs, nil_index_list(),
          rvalue(to_vector(f),
            cons_list(index_multi(ii_obs), nil_index_list()), "to_vector(f)"),
          "assigning variable fobs");
        current_statement__ = 132;
        assign(noise, nil_index_list(),
          multiply(s, stan::math::sqrt(add(fobs, lambda))),
          "assigning variable noise");
        current_statement__ = 149;
        if (heteroscedastic) {
          current_statement__ = 147;
          if (robust) {
            current_statement__ = 145;
            for (int n = 1; n <= N; ++n) {
              current_statement__ = 143;
              lp_accum__.add(
                (lptn(rho, ((y[(n - 1)] - fobs[(n - 1)]) / noise[(n - 1)]),
                   lambdaLPTN, tauLPTN, pstream__) -
                  stan::math::log(noise[(n - 1)])));}
          } else {
            current_statement__ = 141;
            lp_accum__.add(normal_lpdf<false>(y, fobs, noise));
          }
        } else {
          current_statement__ = 139;
          if (robust) {
            current_statement__ = 137;
            for (int n = 1; n <= N; ++n) {
              current_statement__ = 135;
              lp_accum__.add(
                (lptn(rho, ((y[(n - 1)] - fobs[(n - 1)]) / s), lambdaLPTN,
                   tauLPTN, pstream__) - stan::math::log(s)));}
          } else {
            current_statement__ = 133;
            lp_accum__.add(normal_lpdf<false>(y, fobs, s));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_nointeraction_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<double> la_1;
      la_1 = std::vector<double>(la_1_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        current_statement__ = 1;
        assign(la_1, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable la_1");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        current_statement__ = 1;
        assign(la_1, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(la_1[(sym1__ - 1)], 0, 1),
          "assigning variable la_1");}
      std::vector<double> la_2;
      la_2 = std::vector<double>(la_2_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        current_statement__ = 2;
        assign(la_2, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable la_2");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        current_statement__ = 2;
        assign(la_2, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(la_2[(sym1__ - 1)], 0, 1),
          "assigning variable la_2");}
      double log10_ec50_1;
      log10_ec50_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      log10_ec50_1 = in__.scalar();
      double log10_ec50_2;
      log10_ec50_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      log10_ec50_2 = in__.scalar();
      double theta_1;
      theta_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      theta_1 = in__.scalar();
      double theta_2;
      theta_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      theta_2 = in__.scalar();
      double slope_1;
      slope_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      slope_1 = in__.scalar();
      current_statement__ = 7;
      slope_1 = stan::math::lb_constrain(slope_1, 0);
      double slope_2;
      slope_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      slope_2 = in__.scalar();
      current_statement__ = 8;
      slope_2 = stan::math::lb_constrain(slope_2, 0);
      double s;
      s = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 9;
      s = in__.scalar();
      current_statement__ = 9;
      s = stan::math::lb_constrain(s, 0);
      double s2_log10_ec50_1;
      s2_log10_ec50_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 10;
      s2_log10_ec50_1 = in__.scalar();
      current_statement__ = 10;
      s2_log10_ec50_1 = stan::math::lb_constrain(s2_log10_ec50_1, 0);
      double s2_log10_ec50_2;
      s2_log10_ec50_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 11;
      s2_log10_ec50_2 = in__.scalar();
      current_statement__ = 11;
      s2_log10_ec50_2 = stan::math::lb_constrain(s2_log10_ec50_2, 0);
      Eigen::Matrix<double, -1, -1> p0;
      p0 = Eigen::Matrix<double, -1, -1>(n2, n1);
      stan::math::fill(p0, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, 1, -1> p01;
      p01 = Eigen::Matrix<double, 1, -1>(n1);
      stan::math::fill(p01, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> p02;
      p02 = Eigen::Matrix<double, -1, 1>(n2);
      stan::math::fill(p02, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        vars__.emplace_back(la_1[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        vars__.emplace_back(la_2[(sym1__ - 1)]);}
      vars__.emplace_back(log10_ec50_1);
      vars__.emplace_back(log10_ec50_2);
      vars__.emplace_back(theta_1);
      vars__.emplace_back(theta_2);
      vars__.emplace_back(slope_1);
      vars__.emplace_back(slope_2);
      vars__.emplace_back(s);
      vars__.emplace_back(s2_log10_ec50_1);
      vars__.emplace_back(s2_log10_ec50_2);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      {
        double la_1_param;
        la_1_param = std::numeric_limits<double>::quiet_NaN();
        
        double la_2_param;
        la_2_param = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 23;
        if (est_la) {
          current_statement__ = 20;
          la_1_param = la_1[(1 - 1)];
          current_statement__ = 21;
          la_2_param = la_2[(1 - 1)];
        } else {
          current_statement__ = 17;
          la_1_param = 0;
          current_statement__ = 18;
          la_2_param = 0;
        }
        current_statement__ = 30;
        for (int j = 1; j <= n1; ++j) {
          current_statement__ = 24;
          assign(p01, cons_list(index_uni(j), nil_index_list()),
            (la_1_param +
              ((1 - la_1_param) /
                (1 + pow(10, (slope_1 * (x1[(j - 1)] - log10_ec50_1)))))),
            "assigning variable p01");
          current_statement__ = 28;
          for (int i = 1; i <= n2; ++i) {
            current_statement__ = 25;
            assign(p02, cons_list(index_uni(i), nil_index_list()),
              (la_2_param +
                ((1 - la_2_param) /
                  (1 + pow(10, (slope_2 * (x2[(i - 1)] - log10_ec50_2)))))),
              "assigning variable p02");
            current_statement__ = 26;
            assign(p0,
              cons_list(index_uni(i),
                cons_list(index_uni(j), nil_index_list())),
              (p01[(j - 1)] * p02[(i - 1)]), "assigning variable p0");}}
      }
      current_statement__ = 12;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 12;
        for (int sym2__ = 1; sym2__ <= n1; ++sym2__) {
          current_statement__ = 12;
          current_statement__ = 12;
          check_greater_or_equal(function__, "p0[sym1__, sym2__]",
                                 rvalue(p0,
                                   cons_list(index_uni(sym1__),
                                     cons_list(index_uni(sym2__),
                                       nil_index_list())), "p0"), 0);}}
      current_statement__ = 12;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 12;
        for (int sym2__ = 1; sym2__ <= n1; ++sym2__) {
          current_statement__ = 12;
          current_statement__ = 12;
          check_less_or_equal(function__, "p0[sym1__, sym2__]",
                              rvalue(p0,
                                cons_list(index_uni(sym1__),
                                  cons_list(index_uni(sym2__),
                                    nil_index_list())), "p0"), 1);}}
      current_statement__ = 13;
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        current_statement__ = 13;
        current_statement__ = 13;
        check_greater_or_equal(function__, "p01[sym1__]", p01[(sym1__ - 1)],
                               0);}
      current_statement__ = 13;
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        current_statement__ = 13;
        current_statement__ = 13;
        check_less_or_equal(function__, "p01[sym1__]", p01[(sym1__ - 1)], 1);
      }
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_greater_or_equal(function__, "p02[sym1__]", p02[(sym1__ - 1)],
                               0);}
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_less_or_equal(function__, "p02[sym1__]", p02[(sym1__ - 1)], 1);
      }
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n2; ++sym2__) {
            vars__.emplace_back(
              rvalue(p0,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(sym1__), nil_index_list())), "p0"));}}
        for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
          vars__.emplace_back(p01[(sym1__ - 1)]);}
        for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
          vars__.emplace_back(p02[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double ec50_1;
      ec50_1 = std::numeric_limits<double>::quiet_NaN();
      
      double ec50_2;
      ec50_2 = std::numeric_limits<double>::quiet_NaN();
      
      Eigen::Matrix<double, -1, 1> CPO;
      CPO = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(CPO, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 34;
      assign(CPO, nil_index_list(), rep_vector(0, N),
        "assigning variable CPO");
      double dss_1;
      dss_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 35;
      dss_1 = 0;
      double dss_2;
      dss_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 36;
      dss_2 = 0;
      double rVUS_f;
      rVUS_f = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 37;
      rVUS_f = 0;
      double rVUS_p0;
      rVUS_p0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 38;
      rVUS_p0 = 0;
      {
        current_statement__ = 39;
        validate_non_negative_index("f", "n2 + 1", (n2 + 1));
        current_statement__ = 40;
        validate_non_negative_index("f", "n1 + 1", (n1 + 1));
        Eigen::Matrix<double, -1, -1> f;
        f = Eigen::Matrix<double, -1, -1>((n2 + 1), (n1 + 1));
        stan::math::fill(f, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 42;
        validate_non_negative_index("fc_interior", "n2", n2);
        current_statement__ = 43;
        validate_non_negative_index("fc_interior", "n1", n1);
        Eigen::Matrix<double, -1, -1> fc_interior;
        fc_interior = Eigen::Matrix<double, -1, -1>(n2, n1);
        stan::math::fill(fc_interior, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 45;
        validate_non_negative_index("fobs", "N", N);
        Eigen::Matrix<double, -1, 1> fobs;
        fobs = Eigen::Matrix<double, -1, 1>(N);
        stan::math::fill(fobs, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 47;
        validate_non_negative_index("noise", "N", N);
        Eigen::Matrix<double, -1, 1> noise;
        noise = Eigen::Matrix<double, -1, 1>(N);
        stan::math::fill(noise, std::numeric_limits<double>::quiet_NaN());
        
        double la_1_param;
        la_1_param = std::numeric_limits<double>::quiet_NaN();
        
        double la_2_param;
        la_2_param = std::numeric_limits<double>::quiet_NaN();
        
        double c11;
        c11 = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 51;
        c11 = min(x1);
        double c12;
        c12 = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 52;
        c12 = max(x1);
        double c21;
        c21 = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 53;
        c21 = min(x2);
        double c22;
        c22 = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 54;
        c22 = max(x2);
        current_statement__ = 55;
        validate_non_negative_index("B_rVUS", "n2", n2);
        Eigen::Matrix<double, -1, 1> B_rVUS;
        B_rVUS = Eigen::Matrix<double, -1, 1>(n2);
        stan::math::fill(B_rVUS, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 57;
        validate_non_negative_index("B_rVUS_p0", "n2", n2);
        Eigen::Matrix<double, -1, 1> B_rVUS_p0;
        B_rVUS_p0 = Eigen::Matrix<double, -1, 1>(n2);
        stan::math::fill(B_rVUS_p0, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 59;
        assign(f,
          cons_list(index_uni(1), cons_list(index_uni(1), nil_index_list())),
          1, "assigning variable f");
        current_statement__ = 60;
        assign(f,
          cons_list(index_uni(1),
            cons_list(index_min_max(2, (n1 + 1)), nil_index_list())), p01,
          "assigning variable f");
        current_statement__ = 61;
        assign(f,
          cons_list(index_min_max(2, (n2 + 1)),
            cons_list(index_uni(1), nil_index_list())), p02,
          "assigning variable f");
        current_statement__ = 62;
        assign(f,
          cons_list(index_min_max(2, (n2 + 1)),
            cons_list(index_min_max(2, (n1 + 1)), nil_index_list())), p0,
          "assigning variable f");
        current_statement__ = 63;
        assign(fc_interior,
          cons_list(index_min_max(1, n2),
            cons_list(index_min_max(1, n1), nil_index_list())),
          subtract(1, p0), "assigning variable fc_interior");
        current_statement__ = 64;
        assign(fobs, nil_index_list(),
          rvalue(to_vector(f),
            cons_list(index_multi(ii_obs), nil_index_list()), "to_vector(f)"),
          "assigning variable fobs");
        current_statement__ = 65;
        assign(noise, nil_index_list(),
          multiply(s, stan::math::sqrt(add(fobs, lambda))),
          "assigning variable noise");
        current_statement__ = 72;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 70;
          if (heteroscedastic) {
            current_statement__ = 68;
            assign(CPO, cons_list(index_uni(i), nil_index_list()),
              stan::math::exp(
                -normal_lpdf<false>(y[(i - 1)], fobs[(i - 1)],
                   noise[(i - 1)])), "assigning variable CPO");
          } else {
            current_statement__ = 66;
            assign(CPO, cons_list(index_uni(i), nil_index_list()),
              stan::math::exp(
                -normal_lpdf<false>(y[(i - 1)], fobs[(i - 1)], s)),
              "assigning variable CPO");
          }}
        current_statement__ = 73;
        ec50_1 = pow(10, log10_ec50_1);
        current_statement__ = 74;
        ec50_2 = pow(10, log10_ec50_2);
        current_statement__ = 81;
        if (est_la) {
          current_statement__ = 78;
          la_1_param = la_1[(1 - 1)];
          current_statement__ = 79;
          la_2_param = la_2[(1 - 1)];
        } else {
          current_statement__ = 75;
          la_1_param = 0;
          current_statement__ = 76;
          la_2_param = 0;
        }
        current_statement__ = 82;
        dss_1 = ((c12 - c11) +
                  (((la_1_param - 1) / slope_1) *
                    (stan::math::log10(
                       (1 + pow(10, (slope_1 * (c12 - log10_ec50_1))))) -
                      stan::math::log10(
                        (1 + pow(10, (slope_1 * (c11 - log10_ec50_1))))))));
        current_statement__ = 83;
        dss_1 = (100 * (1 - (dss_1 / (c12 - c11))));
        current_statement__ = 84;
        dss_2 = ((c22 - c21) +
                  (((la_2_param - 1) / slope_2) *
                    (stan::math::log10(
                       (1 + pow(10, (slope_2 * (c22 - log10_ec50_2))))) -
                      stan::math::log10(
                        (1 + pow(10, (slope_2 * (c21 - log10_ec50_2))))))));
        current_statement__ = 85;
        dss_2 = (100 * (1 - (dss_2 / (c22 - c21))));
        current_statement__ = 99;
        for (int i = 1; i <= n2; ++i) {
          double b_rVUS;
          b_rVUS = std::numeric_limits<double>::quiet_NaN();
          
          current_statement__ = 86;
          b_rVUS = 0;
          double b_rVUS_p0;
          b_rVUS_p0 = std::numeric_limits<double>::quiet_NaN();
          
          current_statement__ = 87;
          b_rVUS_p0 = 0;
          current_statement__ = 91;
          for (int j = 2; j <= n1; ++j) {
            current_statement__ = 88;
            b_rVUS = (b_rVUS +
                       (((x1[(j - 1)] - x1[((j - 1) - 1)]) *
                          (rvalue(fc_interior,
                             cons_list(index_uni(i),
                               cons_list(index_uni(j), nil_index_list())),
                             "fc_interior") +
                            rvalue(fc_interior,
                              cons_list(index_uni(i),
                                cons_list(index_uni((j - 1)),
                                  nil_index_list())), "fc_interior"))) / 2));
            current_statement__ = 89;
            b_rVUS_p0 = (b_rVUS_p0 +
                          (((x1[(j - 1)] - x1[((j - 1) - 1)]) *
                             ((1 -
                                rvalue(p0,
                                  cons_list(index_uni(i),
                                    cons_list(index_uni(j), nil_index_list())),
                                  "p0")) +
                               (1 -
                                 rvalue(p0,
                                   cons_list(index_uni(i),
                                     cons_list(index_uni((j - 1)),
                                       nil_index_list())), "p0")))) / 2));}
          current_statement__ = 92;
          assign(B_rVUS, cons_list(index_uni(i), nil_index_list()), b_rVUS,
            "assigning variable B_rVUS");
          current_statement__ = 93;
          assign(B_rVUS_p0, cons_list(index_uni(i), nil_index_list()),
            b_rVUS_p0, "assigning variable B_rVUS_p0");
          current_statement__ = 97;
          if (logical_gt(i, 1)) {
            current_statement__ = 94;
            rVUS_f = (rVUS_f +
                       (((x2[(i - 1)] - x2[((i - 1) - 1)]) *
                          (B_rVUS[(i - 1)] + B_rVUS[((i - 1) - 1)])) / 2));
            current_statement__ = 95;
            rVUS_p0 = (rVUS_p0 +
                        (((x2[(i - 1)] - x2[((i - 1) - 1)]) *
                           (B_rVUS_p0[(i - 1)] + B_rVUS_p0[((i - 1) - 1)])) /
                          2));
          } }
        current_statement__ = 100;
        rVUS_f = ((100 * rVUS_f) /
                   ((max(x1) - min(x1)) * (max(x2) - min(x2))));
        current_statement__ = 101;
        rVUS_p0 = ((100 * rVUS_p0) /
                    ((max(x1) - min(x1)) * (max(x2) - min(x2))));
        current_statement__ = 104;
        if (logical_eq(rVUS_f, 0)) {
          current_statement__ = 102;
          rVUS_f = uniform_rng(1e-6, 1e-4, base_rng__);
        } 
        current_statement__ = 107;
        if (logical_eq(rVUS_p0, 0)) {
          current_statement__ = 105;
          rVUS_p0 = uniform_rng(1e-6, 1e-4, base_rng__);
        } 
      }
      vars__.emplace_back(ec50_1);
      vars__.emplace_back(ec50_2);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(CPO[(sym1__ - 1)]);}
      vars__.emplace_back(dss_1);
      vars__.emplace_back(dss_2);
      vars__.emplace_back(rVUS_f);
      vars__.emplace_back(rVUS_p0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      std::vector<double> la_1;
      la_1 = std::vector<double>(la_1_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      assign(la_1, nil_index_list(), context__.vals_r("la_1"),
        "assigning variable la_1");
      std::vector<double> la_1_free__;
      la_1_free__ = std::vector<double>(la_1_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        current_statement__ = 1;
        assign(la_1_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(la_1[(sym1__ - 1)], 0, 1),
          "assigning variable la_1_free__");}
      std::vector<double> la_2;
      la_2 = std::vector<double>(la_2_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      assign(la_2, nil_index_list(), context__.vals_r("la_2"),
        "assigning variable la_2");
      std::vector<double> la_2_free__;
      la_2_free__ = std::vector<double>(la_2_1dim__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        current_statement__ = 2;
        assign(la_2_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(la_2[(sym1__ - 1)], 0, 1),
          "assigning variable la_2_free__");}
      double log10_ec50_1;
      log10_ec50_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      log10_ec50_1 = context__.vals_r("log10_ec50_1")[(1 - 1)];
      double log10_ec50_2;
      log10_ec50_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      log10_ec50_2 = context__.vals_r("log10_ec50_2")[(1 - 1)];
      double theta_1;
      theta_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      theta_1 = context__.vals_r("theta_1")[(1 - 1)];
      double theta_2;
      theta_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      theta_2 = context__.vals_r("theta_2")[(1 - 1)];
      double slope_1;
      slope_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      slope_1 = context__.vals_r("slope_1")[(1 - 1)];
      double slope_1_free__;
      slope_1_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      slope_1_free__ = stan::math::lb_free(slope_1, 0);
      double slope_2;
      slope_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      slope_2 = context__.vals_r("slope_2")[(1 - 1)];
      double slope_2_free__;
      slope_2_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      slope_2_free__ = stan::math::lb_free(slope_2, 0);
      double s;
      s = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 9;
      s = context__.vals_r("s")[(1 - 1)];
      double s_free__;
      s_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 9;
      s_free__ = stan::math::lb_free(s, 0);
      double s2_log10_ec50_1;
      s2_log10_ec50_1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 10;
      s2_log10_ec50_1 = context__.vals_r("s2_log10_ec50_1")[(1 - 1)];
      double s2_log10_ec50_1_free__;
      s2_log10_ec50_1_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 10;
      s2_log10_ec50_1_free__ = stan::math::lb_free(s2_log10_ec50_1, 0);
      double s2_log10_ec50_2;
      s2_log10_ec50_2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 11;
      s2_log10_ec50_2 = context__.vals_r("s2_log10_ec50_2")[(1 - 1)];
      double s2_log10_ec50_2_free__;
      s2_log10_ec50_2_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 11;
      s2_log10_ec50_2_free__ = stan::math::lb_free(s2_log10_ec50_2, 0);
      for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
        vars__.emplace_back(la_1_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
        vars__.emplace_back(la_2_free__[(sym1__ - 1)]);}
      vars__.emplace_back(log10_ec50_1);
      vars__.emplace_back(log10_ec50_2);
      vars__.emplace_back(theta_1);
      vars__.emplace_back(theta_2);
      vars__.emplace_back(slope_1_free__);
      vars__.emplace_back(slope_2_free__);
      vars__.emplace_back(s_free__);
      vars__.emplace_back(s2_log10_ec50_1_free__);
      vars__.emplace_back(s2_log10_ec50_2_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("la_1");
    names__.emplace_back("la_2");
    names__.emplace_back("log10_ec50_1");
    names__.emplace_back("log10_ec50_2");
    names__.emplace_back("theta_1");
    names__.emplace_back("theta_2");
    names__.emplace_back("slope_1");
    names__.emplace_back("slope_2");
    names__.emplace_back("s");
    names__.emplace_back("s2_log10_ec50_1");
    names__.emplace_back("s2_log10_ec50_2");
    names__.emplace_back("p0");
    names__.emplace_back("p01");
    names__.emplace_back("p02");
    names__.emplace_back("ec50_1");
    names__.emplace_back("ec50_2");
    names__.emplace_back("CPO");
    names__.emplace_back("dss_1");
    names__.emplace_back("dss_2");
    names__.emplace_back("rVUS_f");
    names__.emplace_back("rVUS_p0");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(la_1_1dim__)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(la_2_1dim__)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n2),
                                             static_cast<size_t>(n1)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n1)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n2)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "la_1" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "la_2" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "log10_ec50_1");
    param_names__.emplace_back(std::string() + "log10_ec50_2");
    param_names__.emplace_back(std::string() + "theta_1");
    param_names__.emplace_back(std::string() + "theta_2");
    param_names__.emplace_back(std::string() + "slope_1");
    param_names__.emplace_back(std::string() + "slope_2");
    param_names__.emplace_back(std::string() + "s");
    param_names__.emplace_back(std::string() + "s2_log10_ec50_1");
    param_names__.emplace_back(std::string() + "s2_log10_ec50_2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n2; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "p0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "p01" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "p02" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "ec50_1");
      param_names__.emplace_back(std::string() + "ec50_2");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "CPO" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "dss_1");
      param_names__.emplace_back(std::string() + "dss_2");
      param_names__.emplace_back(std::string() + "rVUS_f");
      param_names__.emplace_back(std::string() + "rVUS_p0");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= la_1_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "la_1" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= la_2_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "la_2" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "log10_ec50_1");
    param_names__.emplace_back(std::string() + "log10_ec50_2");
    param_names__.emplace_back(std::string() + "theta_1");
    param_names__.emplace_back(std::string() + "theta_2");
    param_names__.emplace_back(std::string() + "slope_1");
    param_names__.emplace_back(std::string() + "slope_2");
    param_names__.emplace_back(std::string() + "s");
    param_names__.emplace_back(std::string() + "s2_log10_ec50_1");
    param_names__.emplace_back(std::string() + "s2_log10_ec50_2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n2; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "p0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= n1; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "p01" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "p02" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "ec50_1");
      param_names__.emplace_back(std::string() + "ec50_2");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "CPO" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "dss_1");
      param_names__.emplace_back(std::string() + "dss_2");
      param_names__.emplace_back(std::string() + "rVUS_f");
      param_names__.emplace_back(std::string() + "rVUS_p0");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"la_1\",\"type\":{\"name\":\"array\",\"length\":" << la_1_1dim__ << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"la_2\",\"type\":{\"name\":\"array\",\"length\":" << la_2_1dim__ << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"log10_ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log10_ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s2_log10_ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s2_log10_ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"matrix\",\"rows\":" << n2 << ",\"cols\":" << n1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"p01\",\"type\":{\"name\":\"vector\",\"length\":" << n1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"p02\",\"type\":{\"name\":\"vector\",\"length\":" << n2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"CPO\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"dss_1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"dss_2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"rVUS_f\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"rVUS_p0\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"la_1\",\"type\":{\"name\":\"array\",\"length\":" << la_1_1dim__ << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"la_2\",\"type\":{\"name\":\"array\",\"length\":" << la_2_1dim__ << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"log10_ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log10_ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"slope_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s2_log10_ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s2_log10_ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"p0\",\"type\":{\"name\":\"matrix\",\"rows\":" << n2 << ",\"cols\":" << n1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"p01\",\"type\":{\"name\":\"vector\",\"length\":" << n1 << "},\"block\":\"transformed_parameters\"},{\"name\":\"p02\",\"type\":{\"name\":\"vector\",\"length\":" << n2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"ec50_1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"ec50_2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"CPO\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"dss_1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"dss_2\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"rVUS_f\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"rVUS_p0\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_nointeraction_namespace::model_nointeraction;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_nointeraction_namespace::profiles__;
}
#endif
#endif
