# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayeSynGibbs <- function(y_mat, x_mat, model_spec, Alg_param, Hyper_param) {
    .Call('_BayeSyneRgy_BayeSynGibbs', PACKAGE = 'BayeSyneRgy', y_mat, x_mat, model_spec, Alg_param, Hyper_param)
}

GPKernel <- function(x_vec, model_spec) {
    .Call('_BayeSyneRgy_GPKernel', PACKAGE = 'BayeSyneRgy', x_vec, model_spec)
}

computeDelta <- function(Delta_list, x1, x2) {
    .Call('_BayeSyneRgy_computeDelta', PACKAGE = 'BayeSyneRgy', Delta_list, x1, x2)
}

logaccept <- function(y_mat, p_ij_vec, p_ij_vec_new, s2_eps, is_accept) {
    .Call('_BayeSyneRgy_logaccept', PACKAGE = 'BayeSyneRgy', y_mat, p_ij_vec, p_ij_vec_new, s2_eps, is_accept)
}

